#!/bin/bash
# Backup "/media" (Snapshot Style)
SCRIPT_NAME="11-media-ss"

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################

# Snapshot the NAS1 in NAS2

RANDOM_COLOR

if [ ! -d "$LNK_11" ]
then

_CANCEL_MSG

echo -e "Script Warning! Please Check The Script ($SCRIPT_NAME)\n\n 
Reason : The Previous Backup Symlink was not Found"

exit 2

else

if [ -d "$TRG_11_OLD" ]
then
echo "Removing Old Backups"
echo ""
sudo find "$TRG_11_OLD" -maxdepth 1 -type d | sort | tail -n +3 | xargs sudo rm -r
fi

_CHECK_NAS1 && _CHECK_NAS2 \
&& mkdir -p "$TRG_11" \
&& echo "Created Dir: "$TRG_11"" \
&& sudo rsync "${OPT_11[@]}" "$SRC_11" "$TRG_11" \
&& sudo rm -f "$LNK_11" \
&& sudo ln -s "$TRG_11" "$LNK_11" \
&& RANDOM_COLOR && echo -e " $TRG_11 \n--->\n $LNK_11 "


fi

#########################################################


#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF
