#!/bin/bash
# Backup "/home"
SCRIPT_NAME="12-home"

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################

# Sync $HOME to NAS1

if _CHECK_MOUNT1
then



#if [ -d "$TRG_12_OLD" ]
#then
#echo "Removing Old Backups"
#echo ""
#sudo find "$TRG_12_OLD" -maxdepth 1 -type d | sort |head -n -1 |tail -n +2 |xargs rm -r
#fi


# Rsync Backup
if [ "$RSYNC"x = "ON"x ]
then
	sudo rsync "${OPT_12_2[@]}" "$SRC_12_2" "$TRG_12_2"
else
 	echo "Not using Rsync, or maybe no Backup Method was selected,  export <RSYNC|TAR>=ON"
	echo ""
fi

##
##

# Tar Backup
if [ "$TAR"x = "ON"x ]
then
	mkdir -p "$TRG_12"
	rmdir "$TRG_12"
	echo "Created File: $TRG_12-$MIN0.tgz" \
	&& sudo tar "${OPT_12_TAR[@]}" -cpvf "$TRG_12-$MIN0".tgz "$SRC_12"
else
        echo "Not using Tar, or maybe no Backup Method was selected,  export <RSYNC|TAR>=ON"

fi


else

_CANCEL_MSG2

fi
#########################################################


# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

