#!/bin/bash
# Backup "/home/*/.*"
SCRIPT_NAME="18-home-dots"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


# Run <script_name> -c to check if the script is running
if [[ "$1" = "-c"* ]] ;then _LOCK_CHECK ; fi

# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################

if _CHECK_MOUNT1
then

	sudo rsync "${OPT_18[@]}" "$SRC_18"/.* "$TRG_18"

else

_CANCEL_MSG2

fi
#########################################################


# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

