#!/bin/bash
# Adjust brightness of the screen
SCRIPT_NAME="br"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



DISPLAY_BRIGHTNESS()
{
	
		[ "$1" = "OFF" ] && SELECTION1="Both-Monitors"

		[ "$SELECTION1" = "Monitor-1" -o "$SELECTION1" = "Both-Monitors" ] && \
		xrandr --output DVI-I-1 --brightness "$1"

		[ "$SELECTION1" = "Monitor-2" -o "$SELECTION1" = "Both-Monitors" ] && \
		xrandr --output VGA-1 --brightness "$1" && \
		xrandr --output HDMI-1 --brightness "$1"
}
	


[ "$1" = "OFF" ] && DISPLAY_BRIGHTNESS 1.0 && exit 0

SELECTION1="$(dialog --stdout --radiolist "Choose Brightness Level" 13 100 5 \
        "Monitor-1"     "Right" off \
        "Monitor-2"     "Left" off \
        "Both-Monitors" "Right+Left" off)" 


SELECTION2="$(dialog --stdout --radiolist "Choose Brightness Level" 13 100 5 \
        "Very High (Normal)" "" off \
        "High"               "" off \
        "Medium"             "" off \
        "Low"                "" off \
        "Very Low"           "" off)"


if [ "$SELECTION2" = "Very High (Normal)" ]
then
		DISPLAY_BRIGHTNESS 1.0
		
elif [ "$SELECTION2" = "High" ]
then
		DISPLAY_BRIGHTNESS 0.7

elif [ "$SELECTION2" = "Medium" ]
then
		DISPLAY_BRIGHTNESS 0.5

elif [ "$SELECTION2" = "Low" ]
then
		DISPLAY_BRIGHTNESS 0.3

elif [ "$SELECTION2" = "Very Low" ]
then
		DISPLAY_BRIGHTNESS 0.1
fi
