#!/bin/bash
# Adjust brightness of the screen
SCRIPT_NAME="br"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



SELECTION="$(dialog --stdout --checklist "Choose Brightness Level" 13 100 5 \
        "Low-M-1" "" off \
        "Low-M-2" "" off \
        "High"    "" off \
        "Low"     "" off \
        "Normal"  "" off)" 


if [ "$SELECTION" = "Low-M-1" ]
then
	xrandr --output DVI-I-1 --brightness 0.3 && xrandr --output VGA-1 --brightness 1.0 > /dev/null

elif [ "$SELECTION" = "Low-M-2" ]
then
	xrandr --output VGA-1 --brightness 0.3 ; xrandr --output HDMI-1 --brightness 0.3 ; xrandr --output DVI-I-1 --brightness 1.0 > /dev/null

elif [ "$SELECTION" = "High" ]
then
	xrandr --output DVI-I-1 --brightness 1.0 ; xrandr --output VGA-1 --brightness 0.5 ; xrandr --output HDMI-1 --brightness 1.0
	xbrightness 40000 34000 20000

elif [ "$SELECTION" = "Low" ]
then
	xrandr --output DVI-I-1 --brightness 0.1 ; xrandr --output VGA-1 --brightness 0.2 ; xrandr --output HDMI-1 --brightness 0.3 > /dev/null

elif [ "$SELECTION" = "Normal" ]
then
	xrandr --output DVI-I-1 --brightness 1.0 && xrandr --output VGA-1 --brightness 1.0
	xbrightness 63000
fi

