#!/bin/bash
# Adjust brightness of the screen
SCRIPT_NAME="br"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


SELECTION1="$(dialog --stdout --checklist "Choose Brightness Level" 13 100 5 \
        "Monitor-1"     "" off \
        "Monitor-2"     "" off \
        "Both-Monitors" "" off)" 




SELECTION2="$(dialog --stdout --checklist "Choose Brightness Level" 13 100 5 \
        "Very High" "" off \
        "High"      "" off \
        "Medium"    "" off \
        "Low"       "" off \
        "Very Low"  "" off)"


if [ "$SELECTION2" = "Very High" ]
then
		[ "$SELECTION1" = "Monitor-1" ] && \
		xrandr --output DVI-I-1 --brightness 1.0 > /dev/null

		[ "$SELECTION1" = "Monitor-2" ] && \
		xrandr --output VGA-1 --brightness 1.0
		xrandr --output HDMI-1 --brightness 1.0

elif [ "$SELECTION2" = "High" ]
then
		[ "$SELECTION1" = "Monitor-1" ] && \
		xrandr --output DVI-I-1 --brightness 1.0

		[ "$SELECTION1" = "Monitor-2" ] && \
		xrandr --output VGA-1 --brightness 0.5
		xrandr --output HDMI-1 --brightness 1.0
	xbrightness 40000 34000 20000

elif [ "$SELECTION2" = "Normal" ]
then

		[ "$SELECTION1" = "Monitor-1" ] && \
		xrandr --output DVI-I-1 --brightness 1.0

		[ "$SELECTION1" = "Monitor-2" ] && \
		xrandr --output VGA-1 --brightness 1.0
		xrandr --output HDMI-1 --brightness 1.0
	xbrightness 63000

elif [ "$SELECTION2" = "Low" ]
then
	
		[ "$SELECTION1" = "Monitor-1" ] && \
		xrandr --output DVI-I-1 --brightness 0.1

		[ "$SELECTION1" = "Monitor-2" ] && \
		xrandr --output VGA-1 --brightness 0.2
		xrandr --output HDMI-1 --brightness 0.3 > /dev/null


elif [ "$SELECTION2" = "Very Low" ]
then
	
		[ "$SELECTION1" = "Monitor-1" ] && \
		xrandr --output DVI-I-1 --brightness 0.1

		[ "$SELECTION1" = "Monitor-2" ] && \
		xrandr --output VGA-1 --brightness 0.2
		xrandr --output HDMI-1 --brightness 0.3
fi
