#!/bin/bash

SCRIPT_NAME="clean-tilde-backups"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



sudo find /usr/local/bin/ -name "*~" -exec sudo rm -v {} \;
sudo find $MYHOME/ -name "*~" -exec sudo rm -v {} \;

