#!/bin/bash
# Clean the download folder from junk
SCRIPT_NAME="clean-download-folder"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


# Run <script_name> -c to check if the script is running
if [[ "$1" = "-c"* ]] ;then _LOCK_CHECK ; fi

# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################

# Fix Permissions
sudo find "$TV_DOWNLOAD_DIR"/ -exec sudo chmod 777 {} \; -exec sudo chown abz {} \; 2>/dev/null

# Junk
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.directory" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname ".*.log" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.jp*g" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.png" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.txt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.md5" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.bmp" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.gif" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.nfo" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.url" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.htm" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.html" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.smi" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*.rtf" -exec sudo rm {} \; 2>/dev/null

# Subs
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*ara.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*arabic.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*bulgarian.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*chi.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*croatian.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*chs.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*czech.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*dan.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*danish.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*dut.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*dutch.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*fre.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*french.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*gre.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*greek.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*german.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*hrv.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*hun.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*hungarian.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*finnish.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*ita.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*per.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*por-BR.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*portuguese.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*norwegian.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*por.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*polish.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*rum.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*romanian.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*slv.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*spa.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*spanish.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*srp.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*swe.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*swedish.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*serbian.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*tur.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*turkish.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*vie.srt" -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -iname "*vietnamese.srt" -exec sudo rm {} \; 2>/dev/null

# Samples
sudo find "$TV_DOWNLOAD_DIR"/ -type d -iname "sample" -exec sudo rm -r {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -type f -iname "*sample.*" -size -200M -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -type f -iname "RARBG.com.mp4" -size -200M -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -type f -iname "RARBG.com.mkv" -size -200M -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -type f -iname "RARBG.com.avi" -size -200M -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -type f -iname "ETRG.mp4" -size -200M -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -type f -iname "ETRG.mkv" -size -200M -exec sudo rm {} \; 2>/dev/null
sudo find "$TV_DOWNLOAD_DIR"/ -type f -iname "ETRG.avi" -size -200M -exec sudo rm {} \; 2>/dev/null

# My folders
sudo find "$TV_DOWNLOAD_DIR"/ -type d -not -iname "zNew Folder" -exec sudo rmdir {} \; 2>/dev/null



echo "Fixing Subtitles, If any!!!"
sudo find "$TV_DOWNLOAD_DIR"/ -type f -name "*.srt" -exec sed -i '/Subtitles downloaded from www.OpenSubtitles.org/d;/Best watched using Open Subtitles MKV Player/d;/Support us and become VIP member/d;/to remove all ads from OpenSubtitles.org/d;/Advertise your product or brand here/d;/contact www.OpenSubtitles.org today/d' {} \; -exec echo {} \;


#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

