#!/bin/bash

# No-IP uses emails as passwords, so make sure that you encode the @ as %40
USERNAME="$(cat ~/.ddns-user)"
PASSWORD="$(cat ~/.ddns-password)"
HOST=sderawi.com
LOGFILE=/var/log/noip.log
STOREDIPFILE=/var/log/current_ip
USERAGENT="Simple Bash No-IP updater"


	sudo touch $STOREDIPFILE
	sudo chmod 777 $STOREDIPFILE
	sudo touch $LOGFILE
	sudo chmod 777 $LOGFILE



NEWIP=$(wget -4 -q  -O - icanhazip.com)
STOREDIP=$(cat $STOREDIPFILE)

	wget -O "$LOGFILE" -q --no-check-certificate "https://$USERNAME:$PASSWORD@dynupdate.no-ip.com/nic/update?hostname=$HOST&myip=$NEWIP"

	echo "Setting new IP to :$NEWIP"

exit 0

