#!/bin/bash
# Remove the Hardlink connection from files
SCRIPT_NAME="delink"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



tmpfile="$1-$(date)"
sudo cp -a "$1" "$tmpfile"
sudo mv "$tmpfile" "$1"        
RED
echo -n "(De-linked)"
COLOR_OFF
echo -n "$1"

