#!/bin/bash

SCRIPT_NAME="e1"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

trap "rmdir $OPEN_DIR_ECRYPT 2>/dev/null ; exit" INT TERM EXIT


if findmnt -S "$ENCRYPTED_DIR_ECRYPT" -T "$OPEN_DIR_ECRYPT" >/dev/null
then
echo "Finished Unmounting" ; sudo umount "$OPEN_DIR_ECRYPT" ; sudo rmdir "$OPEN_DIR_ECRYPT"
else
sudo mkdir "$OPEN_DIR_ECRYPT" && sudo mount -t ecryptfs "$ENCRYPTED_DIR_ECRYPT" "$OPEN_DIR_ECRYPT" -o key=passphrase,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=yes,ecryptfs_fnek_sig=49ed065030909e1b;
sudo rmdir "$OPEN_DIR_ECRYPT" 2>/dev/null
fi
