#!/bin/bash
# Easystroke scripts all in one place
SCRIPT_NAME="easystroke-scripts"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



# Close Window
if [ "$1" == "C01" ]  ; then
export MIN=YES ; /usr/local/bin/gesture-helper-close-window
fi

# Close Window Really
if [ "$1" == "C02" ]  ; then
export MIN=NO ; /usr/local/bin/gesture-helper-close-window
fi

# Pidgin Text
if [ "$1" == "C03" ]  ; then
xte 'keydown Control_R' 'keydown Alt_R' 'key 0' 'keyup Control_R' 'keyup Alt_R'
CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))"
wmctrl -a salman &&\
(sleep .2 ; xte "str hello" ; xte "key Return" ; sleep .1 ;\
wmctrl -a "$CURRENTWIN" \
notify-send "Pidgin" "Sent hello to Salman") || notify-send "Gesture" "Pidgin window Not Found"
fi

# Change Language
if [ "$1" == "C04" ]  ; then
xte "keydown Alt_L"  "keydown Shift_L" "keyup Alt_L"  "keyup Shift_L"
fi

# Visibility -
if [ "$1" == "C05" ]  ; then
xte "keydown Control_R"  "keydown Alt_L"  "str rrr" "keyup Control_R" "keyup Alt_L"
fi

# Visibility +
if [ "$1" == "C06" ]  ; then
xte "keydown Control_R"  "keydown Alt_L"  "str qqqqqqqqqqqqqqq" "keyup Control_R" "keyup Alt_L"
fi

# File Manager
if [ "$1" == "C07" ]  ; then
dolphin
fi

# Terminal
if [ "$1" == "C08" ]  ; then
terminator
fi

# Brightness
if [ "$1" == "C09" ]  ; then
/usr/local/bin/br
fi

# Search Google
if [ "$1" == "C10" ] ; then
wmctrl -a firefox && xte "keydown Control_R" "key t" "key k" "keyup Control_R"
fi

# Search Google-2
if [ "$1" == "C11" ] ; then
wmctrl -a firefox && xte "keydown Control_R" "key t" "key k" "keyup Control_R"
sleep 3 ; xdotool type "$(xclip -o)" ; xdotool key Return
fi

# ln2tb-Movies
if [ "$1" == "C12" ] ; then
export TERM_LAUNCH=Y ; terminator -x c.ln2tb-movie-find-single
fi

# Search YT - KAT - TVDB
if [ "$1" == "C13" ] ; then
YT_NAME="$(   xclip -o  | sed 's/(//g;s/)//g;s/&/and/g;s/\ /+/g' )"
KAT_NAME="$(  xclip -o  | sed "s/(//g;s/)//g;s/\./\+/g;s/&/and/g;s/,/\ /g;s/'//g;s/\!//g" )"
TVDB_NAME="$( xclip -o  | sed 's/(//g;s///g;s/&/and/g;s/\ /+/g' )"
# YT
firefox "www.youtube.com/results?search_query=$YT_NAME&sm=3" 2>/dev/null
# KAT
firefox "http://kickass.to/usearch/$KAT_NAME" 2>/dev/null
# TVDB
firefox "http://thetvdb.com/?string=$TVDB_NAME&searchseriesid=&tab=listseries&function=Search"
fi

# Search YT & KAT
if [ "$1" == "C14" ] ; then
YT_NAME="$(  xclip -o  | sed 's/(//g;s/)//g;s/&/and/g;s/\ /+/g' )"
KAT_NAME="$( xclip -o  | sed "s/(//g;s/)//g;s/\./\+/g;s/&/and/g;s/,/\ /g;s/'//g;s/\!//g" )"
# YT
firefox "www.youtube.com/results?search_query=$YT_NAME&sm=3" 2>/dev/null
# KAT
firefox "http://kickass.to/usearch/$KAT_NAME" 2>/dev/null
fi

# Search KAT
if [ "$1" == "C15" ] ; then
KAT_NAME="$( xclip -o  | sed "s/(//g;s/)//g;s/\./\+/g;s/&/and/g;s/,/\ /g;s/'//g;s/\!//g" )"
# KAT
firefox "http://kickass.to/usearch/$KAT_NAME" 2>/dev/null
fi

# Move p2p
if [ "$1" == "C16" ] ; then
mv ~/Downloads/*.torrent ~/NAS/Other/Downloads/shared-folder/
mv ~/Downloads/*.nzb ~/NAS/Other/Downloads/shared-folder/
fi

# Pause VLC
if [ "$1" == "C17" ] ; then
CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))"
wmctrl -a "VLC media player" &&\
( sleep .1 ; xte 'key space' ; wmctrl -a "$CURRENTWIN" )
fi

# Fullscreen VLC
if [ "$1" == "C18" ] ; then
xte 'keydown Control_R' 'keydown Alt_R' 'key 0' 'keyup Control_R' 'keyup Alt_R'
CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))"
wmctrl -a "VLC media player" &&\
( sleep .1 ; xte 'key f' ; wmctrl -a "$CURRENTWIN" )
fi

# Fullscreen + Pause VLC
if [ "$1" == "C19" ] ; then
xte 'keydown Control_R' 'keydown Alt_R' 'key 0' 'keyup Control_R' 'keyup Alt_R'
CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))"
wmctrl -a "VLC media player" && \
( sleep .1 ; xte 'key space' 'key f' wmctrl -a "$CURRENTWIN" )
fi

# Window Above
if [ "$1" == "C20" ] ; then
WIN="$(wmctrl -lp | grep `xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/'` | cut -d" " -f1)"
wmctrl -i -r "$WIN" -b add,above
fi

# Window Below
if [ "$1" == "C21" ] ; then
WIN="$(wmctrl -lp | grep `xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/'` | cut -d" " -f1)"
wmctrl -i -r "$WIN" -b remove,above
fi

# Firefox Focus
if [ "$1" == "C22" ] ; then
wmctrl -a firefox || (notify-send "Gesture" "Firefox Window Not Found" ; sudo beep)
fi

# Dolphin Focus
if [ "$1" == "C23" ] ; then
wmctrl -a dolphin || (notify-send "Gesture" "Dolphin Window Not Found" ; sudo beep)
fi

# Pidgin Focus
if [ "$1" == "C24" ] ; then
wmctrl -a salman || (notify-send "Gesture" "Pidgin Window Not Found" ; sudo beep)
fi

# KODI Focus
if [ "$1" == "C25" ] ; then
wmctrl -a kodi || (notify-send "Gesture" "KODI Window Not Found" ; sudo beep)
fi

# VLC Focus
if [ "$1" == "C26" ] ; then
wmctrl -a vlc || (notify-send "Gesture" "VLC Window Not Found" ; sudo beep)
fi

# Geany Focus
if [ "$1" == "C27" ] ; then
wmctrl -a geany || (notify-send "Gesture" "Geany Window Not Found" ; sudo beep)
fi

# Open Keyboard
if [ "$1" == "C28" ] ; then
killall florence ; florence
fi

# Volume UP
if [ "$1" == "C29" ] ; then
xte "keydown Control_R" "keydown Alt_L" "str bbbb" "keyup Control_R" "keyup Alt_L"
fi

# Volume Down
if [ "$1" == "C30" ] ; then
xte "keydown Control_R" "keydown Alt_L" "str nnnn" "keyup Control_R" "keyup Alt_L"
fi

# Press CTRL+SHIFT
if [ "$1" == "C31" ] ; then
xte "keydown Control_L" "keydown Shift_R"
sleep 3
xte "keyup Control_L" "keyup Shift_R"
notify-send "Gesture" "keyup CTRL+SHIFT"
fi

# Press CTRL
if [ "$1" == "C32" ] ; then
xte "keydown Control_L"
sleep 3
xte "keyup Control_L"
notify-send "Gesture" "keyup CTRL"
fi

# Show-Time
if [ "$1" == "C33" ] ; then
/usr/local/bin/show-time
fi

# Select Text & Delete
if [ "$1" == "C34" ] ; then
xte "keydown Control_L" "key a" "keyup Control_L" "key BackSpace" "key BackSpace"
fi

# VLC Jump Forward
if [ "$1" == "C35" ] ; then
CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))"
wmctrl -a "VLC media player" &&\
( sleep .1 ; xte "keydown Control_L" "key Right" "keyup Control_L" ; wmctrl -a "$CURRENTWIN" )
fi

# VLC Jump Back
if [ "$1" == "C36" ] ; then
CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))"
wmctrl -a "VLC media player" &&\
( sleep .1 ; xte "keydown Control_L" "key Left" "keyup Control_L" ; wmctrl -a "$CURRENTWIN" )
fi



# END OF FILE
if [ -z "$1" ] ; then
echo "USAGE: $SCRIPT_NAME C##"
echo "Nothing left to do or no options were passed"
fi
