#!/bin/bash
# Easystroke scripts all in one place
SCRIPT_NAME="easystroke-scripts"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


if [ ! -z "$C1" ]  && (export MIN=YES ; /usr/local/bin/gesture-helper-close-window)
if [ ! -z "$C2" ]  && (export MIN=NO ; /usr/local/bin/gesture-helper-close-window)
if [ ! -z "$C3" ]  && (xte 'keydown Control_R' 'keydown Alt_R' 'key 0' 'keyup Control_R' 'keyup Alt_R' ; CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))" ; wmctrl -a salman ; sleep .2 ; xte "key h" "key e" "key l" "key l" "key o"  ; xte "key Return" ; sleep .1 ; wmctrl -a "$CURRENTWIN" ; notify-send "Pidgin" "Sent hello to Salman")
if [ ! -z "$C4" ]  && (xte "keydown Alt_L"  "keydown Shift_L" "keyup Alt_L"  "keyup Shift_L")
if [ ! -z "$C5" ]  && (xte "keydown Control_R"  "keydown Alt_L"  "key r" "key r" "key r" "keyup Control_R" "keyup Alt_L")
if [ ! -z "$C6" ]  && (KEY="key q" ; xte "keydown Control_R"  "keydown Alt_L"  "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "$KEY" "keyup Control_R" "keyup Alt_L")
if [ ! -z "$C7" ]  && (dolphin)
if [ ! -z "$C8" ]  && (terminator)
if [ ! -z "$C9" ]  && (br)
if [ ! -z "$C10" ] && (wmctrl -a firefox && xte "keydown Control_R" "key t" "key k" "keyup Control_R")
if [ ! -z "$C11" ] && (wmctrl -a firefox && xte "keydown Control_R" "key t" "key k" "keyup Control_R" ; sleep 3 ; xdotool type "$(xclip -o)" ; xdotool key Return)
if [ ! -z "$C12" ] && (export TERM_LAUNCH=Y ; terminator -x c.ln2tb-movie-find-single)
if [ ! -z "$C13" ] && (firefox "www.youtube.com/results?search_query=$(xclip -o|sed 's/(//g;s/)//g;s/&/and/g;s/\ /+/g')&sm=3" ; firefox "http://kickass.to/usearch/$(xclip -o|sed "s/(//g;s/)//g;s/\./\+/g;s/&/and/g;s/,/\ /g;s/'//g;s/\!//g")" ; firefox "http://thetvdb.com/?string=$(xclip -o|sed 's/(//g;s/)//g;s/&/and/g;s/\ /+/g')&searchseriesid=&tab=listseries&function=Search")
if [ ! -z "$C14" ] && (firefox "www.youtube.com/results?search_query=$(xclip -o|sed 's/(//g;s/)//g;s/&/and/g;s/\ /+/g')&sm=3" ; firefox "http://kickass.to/usearch/$(xclip -o|sed "s/(//g;s/)//g;s/\./\+/g;s/&/and/g;s/,/\ /g;s/'//g;s/\!//g")")
if [ ! -z "$C15" ] && (firefox "http://kickass.to/usearch/$(xclip -o|sed "s/(//g;s/)//g;s/\./\+/g;s/&/and/g;s/,/\ /g;s/'//g;s/\!//g")")
if [ ! -z "$C16" ] && (mv ~/Downloads/*.torrent ~/NAS/Other/Downloads/shared-folder/ ; mv ~/Downloads/*.nzb ~/NAS/Other/Downloads/shared-folder/)
if [ ! -z "$C17" ] && (CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))" ; wmctrl -a "VLC media player" && sleep .1 && xte 'key space' ; wmctrl -a "$CURRENTWIN")
if [ ! -z "$C18" ] && (xte 'keydown Control_R' 'keydown Alt_R' 'key 0' 'keyup Control_R' 'keyup Alt_R' ; CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))" ; wmctrl -a "VLC media player" ; sleep .1 ; xte 'key f' ; wmctrl -a "$CURRENTWIN")
if [ ! -z "$C19" ] && (xte 'keydown Control_R' 'keydown Alt_R' 'key 0' 'keyup Control_R' 'keyup Alt_R' ; CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))" ; wmctrl -a "VLC media player" ; sleep .1 ; xte 'key space' 'key f' ; wmctrl -a "$CURRENTWIN")
if [ ! -z "$C20" ] && (WIN="$(wmctrl -lp | grep `xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/'` | cut -d" " -f1)"; wmctrl -i -r $WIN -b add,above)
if [ ! -z "$C21" ] && (WIN="$(wmctrl -lp | grep `xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/'` | cut -d" " -f1)"; wmctrl -i -r $WIN -b remove,above)
if [ ! -z "$C22" ] && (wmctrl -a firefox)
if [ ! -z "$C23" ] && (wmctrl -a dolphin)
if [ ! -z "$C24" ] && (wmctrl -a salman)
if [ ! -z "$C25" ] && (wmctrl -a kodi)
if [ ! -z "$C26" ] && (wmctrl -a vlc)
if [ ! -z "$C27" ] && (wmctrl -a geany)
if [ ! -z "$C28" ] && (killall florence ; florence)
if [ ! -z "$C29" ] && (KEY="key b" ; xte "keydown Control_R"  "keydown Alt_L"   "$KEY" "keyup Control_R" "keyup Alt_L")
if [ ! -z "$C30" ] && (KEY="key n" ; xte "keydown Control_R"  "keydown Alt_L"  "$KEY" "keyup Control_R" "keyup Alt_L")
if [ ! -z "$C31" ] && (xte "keydown Control_L" "keydown Shift_R" ; sleep 3 ;  xte "keyup Control_L" "keyup Shift_R" ; notify-send "Gesture" "keyup CTRL+SHIFT")
if [ ! -z "$C32" ] && (xte "keydown Control_L" ; sleep 3 ;  xte "keyup Control_L" ; notify-send "Gesture" "keyup CTRL")
if [ ! -z "$C33" ] && (/usr/local/bin/show-time)
if [ ! -z "$C34" ] && (xte "keydown Control_L" "key a" "keyup Control_L" "key BackSpace" "key BackSpace")
