#!/bin/bash
# find episodes missing in sal's library
SCRIPT_NAME="find-missing-in-sal"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


Dropbox="$DROPBOX/TV/lists"

cd "$Dropbox" || exit 1

echo "Deleting old list files"

rm -v abz*.txt 2>/dev/null
rm -v sal[2345]*.txt 2>/dev/null
rm -v c*.txt 2>/dev/null

echo "Populating the episodes file"

find "$TV_SYM"  -type f  -size +20M > abz1.txt

while read f ; do basename "$f" | cut -d "]" -f1 >> abz2.txt ;done < abz1.txt 
while read f ; do basename "$f" | cut -d "]" -f1 >> sal2.txt ;done < sal1.txt

cut -d "]" -f1 *2.txt | sed "s/\[/\\\[/g" | sort -f |uniq -u > c1.txt

while read -r a ; do grep -q "$a" abz1.txt && echo "$a    -    is in abz only" ; done < c1.txt > sal-missing.txt
while read -r a ; do grep -q "$a" sal1.txt && echo "$a    -    is in sal only" ; done < c1.txt > abz-missing.txt


echo "Finished - check ($DROPBOX)"
