#!/bin/bash
# find episodes missing from sal's library
SCRIPT_NAME="find-missing-from-sal"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


Dropbox="$DROPBOX/TV/lists"

cd "$Dropbox" || exit 1

echo "Deleting old list files"

rm .abz[12].txt 2>/dev/null
rm .sal2.txt 2>/dev/null
rm .c*.txt 2>/dev/null
rm *missing*.txt 2>/dev/null

echo ""
echo "Populating the episodes file"

find "$TV_SYM"  -type f  -size +20M -exec basename {} \; > .abz1.txt

echo ""
echo "Manipulating the episodes file"

while read f ; do basename "$f" | cut -d "]" -f1 ;done < .sal1.txt >> .sal2.txt

sed "s/\[/\\\[/g" .abz1.txt > .abz2.txt
sed -i "s/\[/\\\[/g" .sal2.txt

cut -d "]" -f1  .abz2.txt .sal2.txt | sort -f |uniq -u > .c1.txt
sed -i "s/\[/\\\[/g" .c1.txt

echo ""
echo "Finalizing the episodes file"

while read -r a ; do grep -q "$a" .abz1.txt && echo "$a    -    is in abz only" ; done < .c1.txt > sal-missing.txt
while read -r a ; do grep -q "$a" .sal1.txt && echo "$a    -    is in sal only" ; done < .c1.txt > abz-missing.txt


echo "Finished - check ($Dropbox)"
