#!/bin/bash
# find episodes missing from sal's library
SCRIPT_NAME="find-missing-from-sal"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


Dropbox="$DROPBOX/TV/lists"

cd "$Dropbox" || exit 1

echo "Deleting old list files"

rm .abz[12].txt 2>/dev/null
rm .sal2.txt 2>/dev/null
rm .c*.txt 2>/dev/null
rm *missing*.txt 2>/dev/null

echo ""
echo "Populating the episodes file"

find "$TV_SYM"  -type f  -size +20M > .abz1.txt

echo ""
echo "Manipulating the episodes file"

while read f ; do basename "$f" | cut -d "]" -f1 ;done < .abz1.txt >> .abz2.txt
while read f ; do basename "$f" | cut -d "]" -f1 ;done < .sal1.txt >> .sal2.txt

cut -d "]" -f1  .abz2.txt .sal2.txt | sort -f | uniq -u > .c1.txt
sed -i "s/\[/\\\[/g" .c1.txt



echo ""
echo "Finalizing the episodes file"

while read -r a ; do grep -q "$a" .abz1.txt && echo "$a    -    is in abz only" ; done < .c1.txt > sal-missing.txt
while read -r a ; do grep -q "$a" .sal1.txt && echo "$a    -    is in sal only" ; done < .c1.txt > abz-missing.txt


cat abz-missing.txt \
| grep -v "1000 Ways To Die" \
| grep -v "30 Days" \
| grep -v "Alaska State Troopers" \
| grep -v "Alcatraz" \
| grep -v "All Worked Up" \
| grep -v "American Guns" \
| grep -v "Border Wars" \
| grep -v "Breaking In" \
| grep -v "Breakout Kings" \
| grep -v "Cake Boss" \
| grep -v "Car Warriors" \
| grep -v "Chip n Dale Rescue Rangers" \
| grep -v "Cow and Chicken" \
| grep -v "Customs" \
| grep -v "Deadliest Warrior" \
| grep -v "Destroyed in Seconds" \
| grep -v "Detroit 1-8-7" \
| grep -v "Dexter\'s Lab" \
| grep -v "Dexters Laboratory" \
| grep -v "Dirty Sexy Money" \
| grep -v "Drugs, Inc." \
| grep -v "Extreme Couponing" \
| grep -v "FlashForward" \
| grep -v "Full Throttle Saloon" \
| grep -v "Hairy Bikers (US)" \
| grep -v "Hardcore Pawn" \
| grep -v "Hillbilly Handfishin" \
| grep -v "Hoarders" \
| grep -v "Hustle" \
| grep -v "Ice Pilots NWT" \
| grep -v "Ice Road Truckers" \
| grep -v "Invention USA" \
| grep -v "Lizard Lick Towing" \
| grep -v "Lock N Load with R. Lee Ermey" \
| grep -v "Look Around You" \
| grep -v "Luck" \
| grep -v "Man v. Food" \
| grep -v "Mas Roadhouse" \
| grep -v "Men of a Certain Age" \
| grep -v "Metalocalypse" \
| grep -v "Moonshiners" \
| grep -v "Mountain Men" \
| grep -v "No Ordinary Family" \
| grep -v "One Man Army" \
| grep -v "Parks and Recreation" \
| grep -v "Pawn Stars" \
| grep -v "Robot Chicken" \
| grep -v "Scare Tactics" \
| grep -v "Sirens (2014)" \
| grep -v "Sister Wives" \
| grep -v "Sleeper Cell" \
| grep -v "Sons of Guns" \
| grep -v "Spawn" \
| grep -v "Steven Seagal Lawman" \
| grep -v "Strike Back" \
| grep -v "Superman The Animated Series" \
| grep -v "Surprise Homecoming" \
| grep -v "Swords Life on the Line" \
| grep -v "Take the Money and Run" \
| grep -v "Teachers (2016)" \
| grep -v "Thats Impossible\!" \
| grep -v "The After" \
| grep -v "The Boondocks" \
| grep -v "The Bridge" \
| grep -v "The Defenders (2010)" \
| grep -v "The Event" \
| grep -v "The Good Guys (2010)" \
| grep -v "The Ren and Stimpy Show" \
| grep -v "The Venture Bros." \
| grep -v "Thundercats" \
| grep -v "Underbelly" > abz-missing-really.txt


echo "Finished - check ($Dropbox)"
