#!/bin/bash
# find episodes missing in sal's library
SCRIPT_NAME="find-missing-in-sal"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


Dropbox="$DROPBOX/TV/lists"

cd "$Dropbox" || exit 1

find "$TV_SYM"  -type f  -size +20M > abz1.txt
sed -i "s/\/home\/sal\/TV\/Shows\//d;s/\/home\/abz\/NAS\/Shows\//d" *1.txt
cut -d "]" -f1 abz1.txt > abz2.txt
cut -d "]" -f1 sal1.txt > sal2.txt
diff -i sal2.txt abz2.txt | grep -E '<' > sal3-missing.txt
diff -i sal2.txt abz2.txt | grep -E '>' > abz3-missing.txt

