#!/bin/bash
# Change gateways easily
SCRIPT_NAME="gateway"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



STATE=$(sudo route -n |grep G )


answer=$(dialog --stdout --backtitle "Choose the Gateway you Desire" --menu "$STATE" 14 70 20 "DSL" "" "4G" "" "WLAN" "" "LAN + 4G" "" )

case $? in
0)
if [ "$answer" = "DSL" ]
then
sudo route del default
sudo route add default gw 10.0.0.137
sudo route -n
fi

if [ "$answer" = "4G" ]
then
sudo route del default
sudo route add default gw 10.0.0.139
sudo route -n
fi

if [ "$answer" = "WLAN" ]
then
sudo route del default
sudo route add default gw 10.0.0.136
sudo route -n
fi

if [ "$answer" = "LAN + 4G" ]
then
sudo route del default
sudo route add default gw 10.0.0.139
sudo route add default gw 10.0.0.138
sudo route -n
fi


;;
1)
_CANCEL_MSG ;;
esac

