#!/bin/bash
# Easystroke complementary script for closing windows
SCRIPT_NAME="gesture-helper-close-window"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))" 

if echo "$CURRENTWIN" | grep "Mozilla Firefox" >/dev/null 
then
notify-send "Close Window" "Not Closing Firefox By Gestures \n(Minimizing Instead)"
wmctrl -a firefox ; xdotool windowminimize $(xdotool getactivewindow)

elif echo "$CURRENTWIN" | grep "Friend - Salman"  >/dev/null
then
notify-send "Close Window" "Not Closing Pidgin Chat By Gestures \n(Minimizing Instead)"
wmctrl -a salman ; xdotool windowminimize $(xdotool getactivewindow)

else
xte "keydown Alt_L" "key F4" "keyup Alt_L"
fi
