#!/bin/bash
# Easystroke helper script for closing windows
SCRIPT_NAME="gesture-helper-close-window"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



CURRENTWIN="$(xdotool getwindowname $(xdotool getwindowfocus))" 

if echo "$CURRENTWIN" | grep "Mozilla Firefox" >/dev/null 
then
notify-send "Close Window" "Minimizied Firefox"
wmctrl -a firefox ; xdotool windowminimize $(xdotool getactivewindow)

elif echo "$CURRENTWIN" | grep "Friend - Salman"  >/dev/null
then
notify-send "Close Window" "Minimized Pidgin"
wmctrl -a salman ; xdotool windowminimize $(xdotool getactivewindow)

elif echo "$CURRENTWIN" | grep "KRDC"  >/dev/null
then
notify-send "Close Window" "Minimized KRDC"
wmctrl -a krdc ; xdotool windowminimize $(xdotool getactivewindow)

else
xte "keydown Alt_L" "key F4" "keyup Alt_L"
fi
