#!/bin/bash
# Do all the git shit

cd /usr/local/bin
git add -A . ; git commit -m N/A ; git push origin


cd /home/abz/Open-Office/Tips-and-Tricks
git add -A . ; git commit -m N/A ; git push origin

cd /home/abz/BTSync-Central-Repo
git add -A . ; git commit -m N/A ; git push origin

