#!/bin/bash
# Search IMDB & KAT for movies gotten through DownThemAll
SCRIPT_NAME="imdb-hunter"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


TMP="$(mktemp)"



cd ~/Downloads/http_/www.imdb.com/title2/ || exit 1


echo "Downloading Movie Data for "$(ls | wc -l)" movies in (~/Downloads/http_/www.imdb.com)"
echo ""

COUNT=0

# Clear the batch file for a fresh start
echo "" >| "$BATCH_FILE_MOVIE_FIND"

for MOVIE in *
do

TITLE="$(curl -s http://www.imdb.com/title/"$MOVIE"/ |grep "<title>" |sed 's/<title>//g ; s/\ -\ IMDb<\/title>//g' | sed 's/^[ \t]*//' | sed 's/&amp;/and/g' )" 

IMDB_NAME="$( echo "$TITLE"  | sed "s/(//g;s/)//g;s/&/and/g;s/\ /+/g" )"
YT_NAME="$(   echo "$TITLE + trailer"  | sed "s/(//g;s/)//g;s/&/and/g;s/\ /+/g" )"
KAT_NAME="$(  echo "$TITLE"  | sed "s/(//g;s/)//g;s/\./\+/g;s/&/and/g;s/,/\ /g;s/'//g;s/\!//g;s/\//+/g" )"
TVDB_NAME="$( echo "$TITLE"  | sed "s/(//g;s///g;s/&/and/g;s/\ /+/g" )"

echo "$TITLE" >> "$BATCH_FILE_MOVIE_FIND"

# IMDB
firefox "http://www.imdb.com/title/$MOVIE" 2>/dev/null
# YT
firefox "www.youtube.com/results?search_query=$YT_NAME&sm=3" 2>/dev/null
# KAT
firefox "https://kickass.cd/usearch/$KAT_NAME" 2>/dev/null
# TVDB
#firefox "http://thetvdb.com/?string=$TVDB_NAME&searchseriesid=&tab=listseries&function=Search"

COUNT=$(($(echo $COUNT) + 1))

if [ $COUNT -gt "9" ]
then COUNT_1="$COUNT"
else COUNT_1="0$COUNT"
fi

echo -en "$COUNT_1) Opening tabs for ${YELLOW}$TITLE"

COLOR_OFF
done

# Find out if we already have the movie
sed -i '/./,$!d' "$BATCH_FILE_MOVIE_FIND" # to delete blank lines from the top of the file

/usr/local/bin/c.ln2tb-movie-find-batch
