#!/bin/bash
# Search IMDB & KAT for movies gotten through DownThemAll
SCRIPT_NAME="imdb-hunter"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


TMP="$(mktemp)"


cd ~/Downloads/http_/www.imdb.com/title/



for i in *
do

curl -s http://www.imdb.com/title/"$i"/|grep "<title>" |sed 's/<title>//g ; s/<\/title>//g' >>| $TMP

done



while read moviename
do
IMDB_NAME="$( cat "$moviename" | sed 's/(//g;s/)//g;s/&/and/g;s/\ /+/g' )"
YT_NAME="$(   cat "$moviename" | sed 's/(//g;s/)//g;s/&/and/g;s/\ /+/g' )"
KAT_NAME="$(  cat "$moviename" | sed "s/(//g;s/)//g;s/\./\+/g;s/&/and/g;s/,/\ /g;s/'//g;s/\!//g" )"

# IMDB
firefox "http://www.imdb.com/find?ref_=nv_sr_fn&q=$IMDB_NAME&s=all"
# YT
firefox "www.youtube.com/results?search_query=$YT_NAME&sm=3"
# KAT
firefox "http://kickass.to/usearch/$KAT_NAME"
done < $TMP
