#!/bin/bash
# Close active window (use with shortcuts)


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


xkill -id "`xprop -root -notype | sed -n '/^_NET_ACTIVE_WINDOW/ s/^.*# *\|\,.*$//g p'`"
