#!/bin/bash

SCRIPT_NAME="LVM"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



sudo systemctl restart lvm2-lvmetad
sudo vgscan
sudo vgchange -an
sudo vgchange -ay
sudo mount -v /mnt/C1 && sudo mount -v /mnt/C1/Other/ISOs/VMs && sudo mount -v /mnt/Backup-Pool
