#!/bin/bash

SCRIPT_NAME="LVM"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



#sudo systemctl restart lvmetad
#sudo vgscan
#sudo vgchange -ay
#sudo mount /dev/mapper/Original-Media /mnt/Original \
#&& startup-programs

