#!/bin/bash
# Use medianfo to gather info about video files
SCRIPT_NAME="mediainfo-helper2"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



if [ ! -f "$1".log ] 
then
mediainfo "$1" | grep -E 'Complete name |File size |Width |Height ' | sed 's/                         :/:/g' > "$1".log
mediainfo "$1" | grep -m 1 'Duration' | sed 's/                         :/:/g' >> "$1".log
#echo -e "\n\n" >> "$1".log
mediainfo "$1" | grep 'Overall bit rate' | grep -v 'Overall bit rate mode' | sed 's/                         :/:/g' >> "$1".log
echo "$1"
fi
