#!/bin/bash

SCRIPT_NAME="media-log"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


export DISPLAY=:0.0


if wmctrl -l |grep SMPlayer 
then
echo "$(date |sed -r 's/AST 201(4|5)//g' )<-> ($(wmctrl -l |grep SMPlayer |cut -d" " -f5- | sed 's/ - SMPlayer2//g' |sed "s/'//g"  ))" > "$PLAYER_LAST_WATCHED"/"$DAY0".txt
else
echo "

Smplayer Not Running

"
fi





if wmctrl -l |grep VLC
then
echo "$(date |sed -r 's/AST 201(4|5)//g' )<-> ($( wmctrl -l |grep VLC |cut -d" " -f5- | sed 's/ - VLC media player//g' |sed "s/'//g" ))" >> "$PLAYER_LAST_WATCHED"/"$DAY0".txt

else
echo "

VLC Not Running

"
fi

