#!/bin/bash
# Use medianfo to gather info about video files
SCRIPT_NAME="mediainfo-helper2"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

FILE="$1"

TMP="$(mktemp)"

if [ ! -f "$FILE".log ] 
then
mediainfo "$FILE" > $TMP

cat $TMP | grep -E 'Complete name |File size |Width |Height ' | sed 's/                         :/:/g' > "$FILE".log
cat $TMP | grep -m 1 'Duration' | sed 's/                         :/:/g' >> "$FILE".log
cat $TMP | grep 'Overall bit rate' | grep -v 'Overall bit rate mode' | sed 's/                         :/:/g' >> "$FILE".log
echo "$FILE".log
fi
