#!/bin/bash
# Use medianfo to gather info about video files
SCRIPT_NAME="mediainfo-helper"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT



mediainfo "$1" | grep -E 'Unique ID |Complete name |File size |Bitrate |Width |Height |Display aspect ratio |Frame rate  |Stream size' | sed 's/                  :/:/g' > "$1".mediainfo
mediainfo "$1" | grep -m 1 'Duration' | sed 's/                  :/:/g' >> "$1".mediainfo

