#!/bin/bash
# Use medianfo to gather info about video files
SCRIPT_NAME="mediainfo-helper2"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

TMP="$(mktemp)"

if [ ! -f "$1".log ] 
then
mediainfo "$1" > $TMP

echo $TMP | grep -E 'Complete name |File size |Width |Height ' | sed 's/                         :/:/g' > "$1".log
echo $TMP | grep -m 1 'Duration' | sed 's/                         :/:/g' >> "$1".log
echo $TMP | grep 'Overall bit rate' | grep -v 'Overall bit rate mode' | sed 's/                         :/:/g' >> "$1".log
echo "$1".log
fi
