#!/bin/bash
# Move episodes to their folders
SCRIPT_NAME="move"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


RED


echo -e "
--------------------------------------------------------------
               Starting File Transfer
--------------------------------------------------------------
"


CYAN

#if [ -f "/media/{"/2 TB"/,"/TB 7"/Downloads}/{Finished,Finished/*}/                "$TV_SYM"/""/ 2>/dev/null && echo -e "nn"

echo "Fixing Subtitles, If there are any!"
sed -i '/Subtitles downloaded from www.OpenSubtitles.org/d;/Best watched using Open Subtitles MKV Player/d' *.srt 2>/dev/null
echo""

if [ "$find_missing_file_move" = "Y" ]
then TV_SYM="$TMP_D/Shows"
else TV_SYM="$TV_SYM"
fi


if ls -U | grep -E '24\ -\ \[*' >/dev/null 2>&1 ; then mv -v 24\ -\ \[* "$TV_SYM"/"24"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E '30\ Rock\ -\ \[*' >/dev/null 2>&1 ; then mv -v 30\ Rock\ -\ \[* "$TV_SYM"/"30 Rock"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E '3rd\ Rock\ from\ the\ Sun\ -\ \[*' >/dev/null 2>&1 ; then mv -v 3rd\ Rock\ from\ the\ Sun\ -\ \[* "$TV_SYM"/"3rd Rock from the Sun"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E '8\ Simple\ Rules\ -\ \[*' >/dev/null 2>&1 ; then mv -v 8\ Simple\ Rules\ -\ \[* "$TV_SYM"/"8 Simple Rules"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'About\ a\ Boy\ -\ \[*' >/dev/null 2>&1 ; then mv -v About\ a\ Boy\ -\ \[* "$TV_SYM"/"About a Boy"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'According\ to\ Jim\ -\ \[*' >/dev/null 2>&1 ; then mv -v According\ to\ Jim\ -\ \[* "$TV_SYM"/"According to Jim"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Almost\ Human\ -\ \[*' >/dev/null 2>&1 ; then mv -v Almost\ Human\ -\ \[* "$TV_SYM"/"Almost Human"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Alpha\ House\ -\ \[*' >/dev/null 2>&1 ; then mv -v Alpha\ House\ -\ \[* "$TV_SYM"/"Alpha House"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'American\ Dad!\ -\ \[*' >/dev/null 2>&1 ; then mv -v American\ Dad!\ -\ \[* "$TV_SYM"/"American Dad!"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'American\ Horror\ Story\ -\ \[*' >/dev/null 2>&1 ; then mv -v American\ Horror\ Story\ -\ \[* "$TV_SYM"/"American Horror Story"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'American\ Restoration\ -\ \[*' >/dev/null 2>&1 ; then mv -v American\ Restoration\ -\ \[* "$TV_SYM"/"American Restoration"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Anger\ Management\ -\ \[*' >/dev/null 2>&1 ; then mv -v Anger\ Management\ -\ \[* "$TV_SYM"/"Anger Management"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Archer\ \(2009\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Archer\ \(2009\)\ -\ \[* "$TV_SYM"/"Archer (2009)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Arrested\ Development\ -\ \[*' >/dev/null 2>&1 ; then mv -v Arrested\ Development\ -\ \[* "$TV_SYM"/"Arrested Development"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Arrow\ -\ \[*' >/dev/null 2>&1 ; then mv -v Arrow\ -\ \[* "$TV_SYM"/"Arrow"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Auction\ Hunters\ -\ \[*' >/dev/null 2>&1 ; then mv -v Auction\ Hunters\ -\ \[* "$TV_SYM"/"Auction Hunters"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Auction\ Kings\ -\ \[*' >/dev/null 2>&1 ; then mv -v Auction\ Kings\ -\ \[* "$TV_SYM"/"Auction Kings"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bad\ Judge\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bad\ Judge\ -\ \[* "$TV_SYM"/"Bad Judge"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bad\ Teacher\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bad\ Teacher\ -\ \[* "$TV_SYM"/"Bad Teacher"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bait\ Car\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bait\ Car\ -\ \[* "$TV_SYM"/"Bait Car"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Banshee\ -\ \[*' >/dev/null 2>&1 ; then mv -v Banshee\ -\ \[* "$TV_SYM"/"Banshee"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Becker\ -\ \[*' >/dev/null 2>&1 ; then mv -v Becker\ -\ \[* "$TV_SYM"/"Becker"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bering\ Sea\ Gold\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bering\ Sea\ Gold\ -\ \[* "$TV_SYM"/"Bering Sea Gold"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bering\ Sea\ Gold\ Under\ the\ Ice\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bering\ Sea\ Gold\ Under\ the\ Ice\ -\ \[* "$TV_SYM"/"Bering Sea Gold Under the Ice"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Betas\ -\ \[*' >/dev/null 2>&1 ; then mv -v Betas\ -\ \[* "$TV_SYM"/"Betas"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Better\ Off\ Ted\ -\ \[*' >/dev/null 2>&1 ; then mv -v Better\ Off\ Ted\ -\ \[* "$TV_SYM"/"Better Off Ted"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Beyond\ Scared\ Straight\ -\ \[*' >/dev/null 2>&1 ; then mv -v Beyond\ Scared\ Straight\ -\ \[* "$TV_SYM"/"Beyond Scared Straight"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Big\ Love\ -\ \[*' >/dev/null 2>&1 ; then mv -v Big\ Love\ -\ \[* "$TV_SYM"/"Big Love"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bitten\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bitten\ -\ \[* "$TV_SYM"/"Bitten"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Black\ Box\ -\ \[*' >/dev/null 2>&1 ; then mv -v Black\ Box\ -\ \[* "$TV_SYM"/"Black Box"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Black\ Gold\ -\ \[*' >/dev/null 2>&1 ; then mv -v Black\ Gold\ -\ \[* "$TV_SYM"/"Black Gold"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Black-ish\ -\ \[*' >/dev/null 2>&1 ; then mv -v Black-ish\ -\ \[* "$TV_SYM"/"Black-ish"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Black\ Jesus\ -\ \[*' >/dev/null 2>&1 ; then mv -v Black\ Jesus\ -\ \[* "$TV_SYM"/"Black Jesus"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Blue\ Bloods\ -\ \[*' >/dev/null 2>&1 ; then mv -v Blue\ Bloods\ -\ \[* "$TV_SYM"/"Blue Bloods"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bobs\ Burgers\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bobs\ Burgers\ -\ \[* "$TV_SYM"/"Bob's Burgers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Body\ of\ Proof\ -\ \[*' >/dev/null 2>&1 ; then mv -v Body\ of\ Proof\ -\ \[* "$TV_SYM"/"Body of Proof"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'BoJack\ Horseman\ -\ \[*' >/dev/null 2>&1 ; then mv -v BoJack\ Horseman\ -\ \[* "$TV_SYM"/"BoJack Horseman"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Border\ Security\ -\ \[*' >/dev/null 2>&1 ; then mv -v Border\ Security\ -\ \[* "$TV_SYM"/"Border Security"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bored\ to\ Death\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bored\ to\ Death\ -\ \[* "$TV_SYM"/"Bored to Death"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bosch\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bosch\ -\ \[* "$TV_SYM"/"Bosch"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Boston\ Legal\ -\ \[*' >/dev/null 2>&1 ; then mv -v Boston\ Legal\ -\ \[* "$TV_SYM"/"Boston Legal"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Boston\ Public\ -\ \[*' >/dev/null 2>&1 ; then mv -v Boston\ Public\ -\ \[* "$TV_SYM"/"Boston Public"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bostons\ Finest\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bostons\ Finest\ -\ \[* "$TV_SYM"/"Boston's Finest"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Boy\ Meets\ World\ -\ \[*' >/dev/null 2>&1 ; then mv -v Boy\ Meets\ World\ -\ \[* "$TV_SYM"/"Boy Meets World"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Breaking\ Bad\ -\ \[*' >/dev/null 2>&1 ; then mv -v Breaking\ Bad\ -\ \[* "$TV_SYM"/"Breaking Bad"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Brickleberry\ -\ \[*' >/dev/null 2>&1 ; then mv -v Brickleberry\ -\ \[* "$TV_SYM"/"Brickleberry"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Brooklyn\ Nine-Nine\ -\ \[*' >/dev/null 2>&1 ; then mv -v Brooklyn\ Nine-Nine\ -\ \[* "$TV_SYM"/"Brooklyn Nine-Nine"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Cajun\ Pawn\ Stars\ -\ \[*' >/dev/null 2>&1 ; then mv -v Cajun\ Pawn\ Stars\ -\ \[* "$TV_SYM"/"Cajun Pawn Stars"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Californication\ -\ \[*' >/dev/null 2>&1 ; then mv -v Californication\ -\ \[* "$TV_SYM"/"Californication"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Castle\ \(2009\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Castle\ \(2009\)\ -\ \[* "$TV_SYM"/"Castle (2009)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chappelles\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v Chappelles\ Show\ -\ \[* "$TV_SYM"/"Chappelle's Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chicago\ Fire\ -\ \[*' >/dev/null 2>&1 ; then mv -v Chicago\ Fire\ -\ \[* "$TV_SYM"/"Chicago Fire"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chicago\ P.D.\ -\ \[*' >/dev/null 2>&1 ; then mv -v Chicago\ P.D.\ -\ \[* "$TV_SYM"/"Chicago P.D."/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chip\ n\ Dale\ Rescue\ Rangers\ -\ \[*' >/dev/null 2>&1 ; then mv -v Chip\ n\ Dale\ Rescue\ Rangers\ -\ \[* "$TV_SYM"/"Chip n Dale Rescue Rangers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chozen\ -\ \[*' >/dev/null 2>&1 ; then mv -v Chozen\ -\ \[* "$TV_SYM"/"Chozen"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chuck\ -\ \[*' >/dev/null 2>&1 ; then mv -v Chuck\ -\ \[* "$TV_SYM"/"Chuck"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Cold\ Case\ -\ \[*' >/dev/null 2>&1 ; then mv -v Cold\ Case\ -\ \[* "$TV_SYM"/"Cold Case"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Come\ Fly\ With\ Me\ -\ \[*' >/dev/null 2>&1 ; then mv -v Come\ Fly\ With\ Me\ -\ \[* "$TV_SYM"/"Come Fly With Me"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Community\ -\ \[*' >/dev/null 2>&1 ; then mv -v Community\ -\ \[* "$TV_SYM"/"Community"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Cops\ -\ \[*' >/dev/null 2>&1 ; then mv -v Cops\ -\ \[* "$TV_SYM"/"Cops"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Counting\ Cars\ -\ \[*' >/dev/null 2>&1 ; then mv -v Counting\ Cars\ -\ \[* "$TV_SYM"/"Counting Cars"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Covert\ Affairs\ -\ \[*' >/dev/null 2>&1 ; then mv -v Covert\ Affairs\ -\ \[* "$TV_SYM"/"Covert Affairs"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Criminal\ Minds\ -\ \[*' >/dev/null 2>&1 ; then mv -v Criminal\ Minds\ -\ \[* "$TV_SYM"/"Criminal Minds"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Crisis\ -\ \[*' >/dev/null 2>&1 ; then mv -v Crisis\ -\ \[* "$TV_SYM"/"Crisis"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Crossbones\ -\ \[*' >/dev/null 2>&1 ; then mv -v Crossbones\ -\ \[* "$TV_SYM"/"Crossbones"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Crossing\ Lines\ -\ \[*' >/dev/null 2>&1 ; then mv -v Crossing\ Lines\ -\ \[* "$TV_SYM"/"Crossing Lines"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'CSI\ Crime\ Scene\ Investigation\ -\ \[*' >/dev/null 2>&1 ; then mv -v CSI\ Crime\ Scene\ Investigation\ -\ \[* "$TV_SYM"/"CSI Crime Scene Investigation"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'CSI\ Miami\ -\ \[*' >/dev/null 2>&1 ; then mv -v CSI\ Miami\ -\ \[* "$TV_SYM"/"CSI Miami"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'CSINY\ -\ \[*' >/dev/null 2>&1 ; then mv -v CSINY\ -\ \[* "$TV_SYM"/"CSINY"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Curb\ Your\ Enthusiasm\ -\ \[*' >/dev/null 2>&1 ; then mv -v Curb\ Your\ Enthusiasm\ -\ \[* "$TV_SYM"/"Curb Your Enthusiasm"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Dads\ \(2013\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Dads\ \(2013\)\ -\ \[* "$TV_SYM"/"Dads (2013)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Damages\ -\ \[*' >/dev/null 2>&1 ; then mv -v Damages\ -\ \[* "$TV_SYM"/"Damages"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Deadbeat\ -\ \[*' >/dev/null 2>&1 ; then mv -v Deadbeat\ -\ \[* "$TV_SYM"/"Deadbeat"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Deadliest\ Catch\ -\ \[*' >/dev/null 2>&1 ; then mv -v Deadliest\ Catch\ -\ \[* "$TV_SYM"/"Deadliest Catch"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Deadwood\ -\ \[*' >/dev/null 2>&1 ; then mv -v Deadwood\ -\ \[* "$TV_SYM"/"Deadwood"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Desperate\ Housewives\ -\ \[*' >/dev/null 2>&1 ; then mv -v Desperate\ Housewives\ -\ \[* "$TV_SYM"/"Desperate Housewives"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Dexter\ -\ \[*' >/dev/null 2>&1 ; then mv -v Dexter\ -\ \[* "$TV_SYM"/"Dexter"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Dirty\ Money\ \(2011\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Dirty\ Money\ \(2011\)\ -\ \[* "$TV_SYM"/"Dirty Money (2011)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Dragons\ Den\ \(Canada\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Dragons\ Den\ \(Canada\)\ -\ \[* "$TV_SYM"/"Dragons' Den (Canada)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Drawn\ Together\ -\ \[*' >/dev/null 2>&1 ; then mv -v Drawn\ Together\ -\ \[* "$TV_SYM"/"Drawn Together"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Drunk\ History\ -\ \[*' >/dev/null 2>&1 ; then mv -v Drunk\ History\ -\ \[* "$TV_SYM"/"Drunk History"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Dual\ Survival\ -\ \[*' >/dev/null 2>&1 ; then mv -v Dual\ Survival\ -\ \[* "$TV_SYM"/"Dual Survival"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Eastbound\ \&\ Down\ -\ \[*' >/dev/null 2>&1 ; then mv -v Eastbound\ \&\ Down\ -\ \[* "$TV_SYM"/"Eastbound & Down"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Enlisted\ -\ \[*' >/dev/null 2>&1 ; then mv -v Enlisted\ -\ \[* "$TV_SYM"/"Enlisted"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Everybody\ Loves\ Raymond\ -\ \[*' >/dev/null 2>&1 ; then mv -v Everybody\ Loves\ Raymond\ -\ \[* "$TV_SYM"/"Everybody Loves Raymond"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Extant\ -\ \[*' >/dev/null 2>&1 ; then mv -v Extant\ -\ \[* "$TV_SYM"/"Extant"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Extreme\ Makeover\ Home\ Edition\ -\ \[*' >/dev/null 2>&1 ; then mv -v Extreme\ Makeover\ Home\ Edition\ -\ \[* "$TV_SYM"/"Extreme Makeover Home Edition"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Face\ Off\ -\ \[*' >/dev/null 2>&1 ; then mv -v Face\ Off\ -\ \[* "$TV_SYM"/"Face Off"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Falling\ Skies\ -\ \[*' >/dev/null 2>&1 ; then mv -v Falling\ Skies\ -\ \[* "$TV_SYM"/"Falling Skies"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Family\ Guy\ -\ \[*' >/dev/null 2>&1 ; then mv -v Family\ Guy\ -\ \[* "$TV_SYM"/"Family Guy"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Fargo\ -\ \[*' >/dev/null 2>&1 ; then mv -v Fargo\ -\ \[* "$TV_SYM"/"Fargo"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Fast\ N\ Loud\ -\ \[*' >/dev/null 2>&1 ; then mv -v Fast\ N\ Loud\ -\ \[* "$TV_SYM"/"Fast N' Loud"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Flashpoint\ -\ \[*' >/dev/null 2>&1 ; then mv -v Flashpoint\ -\ \[* "$TV_SYM"/"Flashpoint"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Forever\ \(2014\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Forever\ \(2014\)\ -\ \[* "$TV_SYM"/"Forever (2014)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Franklin\ \&\ Bash\ -\ \[*' >/dev/null 2>&1 ; then mv -v Franklin\ \&\ Bash\ -\ \[* "$TV_SYM"/"Franklin & Bash"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Frasier\ -\ \[*' >/dev/null 2>&1 ; then mv -v Frasier\ -\ \[* "$TV_SYM"/"Frasier"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Friends\ -\ \[*' >/dev/null 2>&1 ; then mv -v Friends\ -\ \[* "$TV_SYM"/"Friends"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Friends\ with\ Better\ Lives\ -\ \[*' >/dev/null 2>&1 ; then mv -v Friends\ with\ Better\ Lives\ -\ \[* "$TV_SYM"/"Friends with Better Lives"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Fringe\ -\ \[*' >/dev/null 2>&1 ; then mv -v Fringe\ -\ \[* "$TV_SYM"/"Fringe"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Futurama\ -\ \[*' >/dev/null 2>&1 ; then mv -v Futurama\ -\ \[* "$TV_SYM"/"Futurama"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Game\ of\ Thrones\ -\ \[*' >/dev/null 2>&1 ; then mv -v Game\ of\ Thrones\ -\ \[* "$TV_SYM"/"Game of Thrones"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Gang\ Related\ -\ \[*' >/dev/null 2>&1 ; then mv -v Gang\ Related\ -\ \[* "$TV_SYM"/"Gang Related"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'George\ Lopez\ -\ \[*' >/dev/null 2>&1 ; then mv -v George\ Lopez\ -\ \[* "$TV_SYM"/"George Lopez"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Getting\ On\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Getting\ On\ \(US\)\ -\ \[* "$TV_SYM"/"Getting On (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Golden\ Boy\ -\ \[*' >/dev/null 2>&1 ; then mv -v Golden\ Boy\ -\ \[* "$TV_SYM"/"Golden Boy"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Golden\ Boy\ \(2013\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Golden\ Boy\ \(2013\)\ -\ \[* "$TV_SYM"/"Golden Boy (2013)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Gold\ Rush\ -\ \[*' >/dev/null 2>&1 ; then mv -v Gold\ Rush\ -\ \[* "$TV_SYM"/"Gold Rush"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Gotham\ -\ \[*' >/dev/null 2>&1 ; then mv -v Gotham\ -\ \[* "$TV_SYM"/"Gotham"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Graceland\ -\ \[*' >/dev/null 2>&1 ; then mv -v Graceland\ -\ \[* "$TV_SYM"/"Graceland"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Ground\ Floor\ -\ \[*' >/dev/null 2>&1 ; then mv -v Ground\ Floor\ -\ \[* "$TV_SYM"/"Ground Floor"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Growing\ Up\ Fisher\ -\ \[*' >/dev/null 2>&1 ; then mv -v Growing\ Up\ Fisher\ -\ \[* "$TV_SYM"/"Growing Up Fisher"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hand\ of\ God\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hand\ of\ God\ -\ \[* "$TV_SYM"/"Hand of God"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hannibal\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hannibal\ -\ \[* "$TV_SYM"/"Hannibal"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Happy\ Endings\ -\ \[*' >/dev/null 2>&1 ; then mv -v Happy\ Endings\ -\ \[* "$TV_SYM"/"Happy Endings"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hard\ Time\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hard\ Time\ -\ \[* "$TV_SYM"/"Hard Time"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hawaii\ Five-0\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hawaii\ Five-0\ -\ \[* "$TV_SYM"/"Hawaii Five-0"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hell\ on\ Wheels\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hell\ on\ Wheels\ -\ \[* "$TV_SYM"/"Hell on Wheels"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Heroes\ -\ \[*' >/dev/null 2>&1 ; then mv -v Heroes\ -\ \[* "$TV_SYM"/"Heroes"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hill\ Street\ Blues\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hill\ Street\ Blues\ -\ \[* "$TV_SYM"/"Hill Street Blues"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hogans\ Heroes\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hogans\ Heroes\ -\ \[* "$TV_SYM"/"Hogans Heroes"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Home\ Improvement\ -\ \[*' >/dev/null 2>&1 ; then mv -v Home\ Improvement\ -\ \[* "$TV_SYM"/"Home Improvement"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Homeland\ -\ \[*' >/dev/null 2>&1 ; then mv -v Homeland\ -\ \[* "$TV_SYM"/"Homeland"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hostages\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hostages\ -\ \[* "$TV_SYM"/"Hostages"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hot\ in\ Cleveland\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hot\ in\ Cleveland\ -\ \[* "$TV_SYM"/"Hot in Cleveland"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'House\ -\ \[*' >/dev/null 2>&1 ; then mv -v House\ -\ \[* "$TV_SYM"/"House"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'House\ of\ Cards\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v House\ of\ Cards\ \(US\)\ -\ \[* "$TV_SYM"/"House of Cards (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'House\ of\ Lies\ -\ \[*' >/dev/null 2>&1 ; then mv -v House\ of\ Lies\ -\ \[* "$TV_SYM"/"House of Lies"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'How\ Do\ They\ Do\ It\ -\ \[*' >/dev/null 2>&1 ; then mv -v How\ Do\ They\ Do\ It\ -\ \[* "$TV_SYM"/"How Do They Do It"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'How\ I\ Met\ Your\ Mother\ -\ \[*' >/dev/null 2>&1 ; then mv -v How\ I\ Met\ Your\ Mother\ -\ \[* "$TV_SYM"/"How I Met Your Mother"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'How\ Its\ Made\ -\ \[*' >/dev/null 2>&1 ; then mv -v How\ Its\ Made\ -\ \[* "$TV_SYM"/"How Its Made"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'How\ to\ Get\ Away\ with\ Murder\ -\ \[*' >/dev/null 2>&1 ; then mv -v How\ to\ Get\ Away\ with\ Murder\ -\ \[* "$TV_SYM"/"How to Get Away with Murder"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'How\ to\ Live\ with\ Your\ Parents\ -\ \[*' >/dev/null 2>&1 ; then mv -v How\ to\ Live\ with\ Your\ Parents\ -\ \[* "$TV_SYM"/"How to Live with Your Parents"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'How\ to\ Make\ It\ in\ America\ -\ \[*' >/dev/null 2>&1 ; then mv -v How\ to\ Make\ It\ in\ America\ -\ \[* "$TV_SYM"/"How to Make It in America"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Human\ Target\ \(2010\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Human\ Target\ \(2010\)\ -\ \[* "$TV_SYM"/"Human Target (2010)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Ice\ Cold\ Gold\ -\ \[*' >/dev/null 2>&1 ; then mv -v Ice\ Cold\ Gold\ -\ \[* "$TV_SYM"/"Ice Cold Gold"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Impractical\ Jokers\ -\ \[*' >/dev/null 2>&1 ; then mv -v Impractical\ Jokers\ -\ \[* "$TV_SYM"/"Impractical Jokers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Intelligence\ \(2014\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Intelligence\ \(2014\)\ -\ \[* "$TV_SYM"/"Intelligence (2014)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'IRT\ Deadliest\ Roads\ -\ \[*' >/dev/null 2>&1 ; then mv -v IRT\ Deadliest\ Roads\ -\ \[* "$TV_SYM"/"IRT Deadliest Roads"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Its\ Always\ Sunny\ in\ Philadelphia\ -\ \[*' >/dev/null 2>&1 ; then mv -v Its\ Always\ Sunny\ in\ Philadelphia\ -\ \[* "$TV_SYM"/"Its Always Sunny in Philadelphia"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Jackass\ -\ \[*' >/dev/null 2>&1 ; then mv -v Jackass\ -\ \[* "$TV_SYM"/"Jackass"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'JAG\ -\ \[*' >/dev/null 2>&1 ; then mv -v JAG\ -\ \[* "$TV_SYM"/"JAG"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Jail\ -\ \[*' >/dev/null 2>&1 ; then mv -v Jail\ -\ \[* "$TV_SYM"/"Jail"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Jennifer\ Falls\ -\ \[*' >/dev/null 2>&1 ; then mv -v Jennifer\ Falls\ -\ \[* "$TV_SYM"/"Jennifer Falls"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Jungle\ Gold\ -\ \[*' >/dev/null 2>&1 ; then mv -v Jungle\ Gold\ -\ \[* "$TV_SYM"/"Jungle Gold"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Justified\ -\ \[*' >/dev/null 2>&1 ; then mv -v Justified\ -\ \[* "$TV_SYM"/"Justified"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Just\ Shoot\ Me\ -\ \[*' >/dev/null 2>&1 ; then mv -v Just\ Shoot\ Me\ -\ \[* "$TV_SYM"/"Just Shoot Me"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Key\ \&\ Peele\ -\ \[*' >/dev/null 2>&1 ; then mv -v Key\ \&\ Peele\ -\ \[* "$TV_SYM"/"Key & Peele"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'King\ of\ the\ Hill\ -\ \[*' >/dev/null 2>&1 ; then mv -v King\ of\ the\ Hill\ -\ \[* "$TV_SYM"/"King of the Hill"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Kroll\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v Kroll\ Show\ -\ \[* "$TV_SYM"/"Kroll Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Last\ Comic\ Standing\ -\ \[*' >/dev/null 2>&1 ; then mv -v Last\ Comic\ Standing\ -\ \[* "$TV_SYM"/"Last Comic Standing"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Last\ Man\ Standing\ \(2011\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Last\ Man\ Standing\ \(2011\)\ -\ \[* "$TV_SYM"/"Last Man Standing (2011)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Las\ Vegas\ -\ \[*' >/dev/null 2>&1 ; then mv -v Las\ Vegas\ -\ \[* "$TV_SYM"/"Las Vegas"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Las\ Vegas\ Jailhouse\ -\ \[*' >/dev/null 2>&1 ; then mv -v Las\ Vegas\ Jailhouse\ -\ \[* "$TV_SYM"/"Las Vegas Jailhouse"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Legit\ \(2013\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Legit\ \(2013\)\ -\ \[* "$TV_SYM"/"Legit (2013)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Leverage\ -\ \[*' >/dev/null 2>&1 ; then mv -v Leverage\ -\ \[* "$TV_SYM"/"Leverage"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Lie\ to\ me\ -\ \[*' >/dev/null 2>&1 ; then mv -v Lie\ to\ me\ -\ \[* "$TV_SYM"/"Lie to me"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Life\ \(2007\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Life\ \(2007\)\ -\ \[* "$TV_SYM"/"Life (2007)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Lilyhammer\ -\ \[*' >/dev/null 2>&1 ; then mv -v Lilyhammer\ -\ \[* "$TV_SYM"/"Lilyhammer"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Lockup\ -\ \[*' >/dev/null 2>&1 ; then mv -v Lockup\ -\ \[* "$TV_SYM"/"Lockup"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Lost\ -\ \[*' >/dev/null 2>&1 ; then mv -v Lost\ -\ \[* "$TV_SYM"/"Lost"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Louie\ \(2010\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Louie\ \(2010\)\ -\ \[* "$TV_SYM"/"Louie (2010)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Low\ Winter\ Sun\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Low\ Winter\ Sun\ \(US\)\ -\ \[* "$TV_SYM"/"Low Winter Sun (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'MacGyver\ -\ \[*' >/dev/null 2>&1 ; then mv -v MacGyver\ -\ \[* "$TV_SYM"/"MacGyver"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Madam\ Secretary\ -\ \[*' >/dev/null 2>&1 ; then mv -v Madam\ Secretary\ -\ \[* "$TV_SYM"/"Madam Secretary"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mad\ Men\ -\ \[*' >/dev/null 2>&1 ; then mv -v Mad\ Men\ -\ \[* "$TV_SYM"/"Mad Men"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Malcolm\ in\ the\ Middle\ -\ \[*' >/dev/null 2>&1 ; then mv -v Malcolm\ in\ the\ Middle\ -\ \[* "$TV_SYM"/"Malcolm in the Middle"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Man\ Finds\ Food\ -\ \[*' >/dev/null 2>&1 ; then mv -v Man\ Finds\ Food\ -\ \[* "$TV_SYM"/"Man Finds Food"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Manhattan\ -\ \[*' >/dev/null 2>&1 ; then mv -v Manhattan\ -\ \[* "$TV_SYM"/"Manhattan"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Man\ vs.\ Wild\ -\ \[*' >/dev/null 2>&1 ; then mv -v Man\ vs.\ Wild\ -\ \[* "$TV_SYM"/"Man vs. Wild"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Married\ -\ \[*' >/dev/null 2>&1 ; then mv -v Married\ -\ \[* "$TV_SYM"/"Married"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Married\ ...\ with\ Children\ -\ \[*' >/dev/null 2>&1 ; then mv -v Married\ ...\ with\ Children\ -\ \[* "$TV_SYM"/"Married ... with Children"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Marvels\ Agents\ of\ S.H.I.E.L.D.\ -\ \[*' >/dev/null 2>&1 ; then mv -v Marvels\ Agents\ of\ S.H.I.E.L.D.\ -\ \[* "$TV_SYM"/"Marvel's Agents of S.H.I.E.L.D."/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Men\ at\ Work\ -\ \[*' >/dev/null 2>&1 ; then mv -v Men\ at\ Work\ -\ \[* "$TV_SYM"/"Men at Work"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mind\ of\ Mencia\ -\ \[*' >/dev/null 2>&1 ; then mv -v Mind\ of\ Mencia\ -\ \[* "$TV_SYM"/"Mind of Mencia"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mob\ City\ -\ \[*' >/dev/null 2>&1 ; then mv -v Mob\ City\ -\ \[* "$TV_SYM"/"Mob City"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Modern\ Family\ -\ \[*' >/dev/null 2>&1 ; then mv -v Modern\ Family\ -\ \[* "$TV_SYM"/"Modern Family"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mom\ -\ \[*' >/dev/null 2>&1 ; then mv -v Mom\ -\ \[* "$TV_SYM"/"Mom"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Monk\ -\ \[*' >/dev/null 2>&1 ; then mv -v Monk\ -\ \[* "$TV_SYM"/"Monk"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Most\ Daring\ -\ \[*' >/dev/null 2>&1 ; then mv -v Most\ Daring\ -\ \[* "$TV_SYM"/"Most Daring"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mountain\ Men\ -\ \[*' >/dev/null 2>&1 ; then mv -v Mountain\ Men\ -\ \[* "$TV_SYM"/"Mountain Men"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mulaney\ -\ \[*' >/dev/null 2>&1 ; then mv -v Mulaney\ -\ \[* "$TV_SYM"/"Mulaney"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'My\ Five\ Wives\ -\ \[*' >/dev/null 2>&1 ; then mv -v My\ Five\ Wives\ -\ \[* "$TV_SYM"/"My Five Wives"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'My\ Name\ Is\ Earl\ -\ \[*' >/dev/null 2>&1 ; then mv -v My\ Name\ Is\ Earl\ -\ \[* "$TV_SYM"/"My Name Is Earl"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'MythBusters\ -\ \[*' >/dev/null 2>&1 ; then mv -v MythBusters\ -\ \[* "$TV_SYM"/"MythBusters"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'NCIS\ -\ \[*' >/dev/null 2>&1 ; then mv -v NCIS\ -\ \[* "$TV_SYM"/"NCIS"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'NCIS\ Los\ Angeles\ -\ \[*' >/dev/null 2>&1 ; then mv -v NCIS\ Los\ Angeles\ -\ \[* "$TV_SYM"/"NCIS Los Angeles"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Necessary\ Roughness\ -\ \[*' >/dev/null 2>&1 ; then mv -v Necessary\ Roughness\ -\ \[* "$TV_SYM"/"Necessary Roughness"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Nip_Tuck\ -\ \[*' >/dev/null 2>&1 ; then mv -v Nip_Tuck\ -\ \[* "$TV_SYM"/"Nip_Tuck"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Northern\ Exposure\ -\ \[*' >/dev/null 2>&1 ; then mv -v Northern\ Exposure\ -\ \[* "$TV_SYM"/"Northern Exposure"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Nurse\ Jackie\ -\ \[*' >/dev/null 2>&1 ; then mv -v Nurse\ Jackie\ -\ \[* "$TV_SYM"/"Nurse Jackie"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'NYPD\ Blue\ -\ \[*' >/dev/null 2>&1 ; then mv -v NYPD\ Blue\ -\ \[* "$TV_SYM"/"NYPD Blue"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Only\ in\ America\ with\ Larry\ the\ Cable\ Guy\ -\ \[*' >/dev/null 2>&1 ; then mv -v Only\ in\ America\ with\ Larry\ the\ Cable\ Guy\ -\ \[* "$TV_SYM"/"Only in America with Larry the Cable Guy"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Orange\ Is\ the\ New\ Black\ -\ \[*' >/dev/null 2>&1 ; then mv -v Orange\ Is\ the\ New\ Black\ -\ \[* "$TV_SYM"/"Orange Is the New Black"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Oz\ -\ \[*' >/dev/null 2>&1 ; then mv -v Oz\ -\ \[* "$TV_SYM"/"Oz"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Parenthood\ \(2010\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Parenthood\ \(2010\)\ -\ \[* "$TV_SYM"/"Parenthood (2010)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Parking\ Wars\ -\ \[*' >/dev/null 2>&1 ; then mv -v Parking\ Wars\ -\ \[* "$TV_SYM"/"Parking Wars"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Parks\ and\ Recreation\ -\ \[*' >/dev/null 2>&1 ; then mv -v Parks\ and\ Recreation\ -\ \[* "$TV_SYM"/"Parks and Recreation"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Partners\ \(2014\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Partners\ \(2014\)\ -\ \[* "$TV_SYM"/"Partners (2014)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Person\ of\ Interest\ -\ \[*' >/dev/null 2>&1 ; then mv -v Person\ of\ Interest\ -\ \[* "$TV_SYM"/"Person of Interest"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Pimp\ My\ Ride\ -\ \[*' >/dev/null 2>&1 ; then mv -v Pimp\ My\ Ride\ -\ \[* "$TV_SYM"/"Pimp My Ride"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Playing\ House\ -\ \[*' >/dev/null 2>&1 ; then mv -v Playing\ House\ -\ \[* "$TV_SYM"/"Playing House"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Prison\ Break\ -\ \[*' >/dev/null 2>&1 ; then mv -v Prison\ Break\ -\ \[* "$TV_SYM"/"Prison Break"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Psych\ -\ \[*' >/dev/null 2>&1 ; then mv -v Psych\ -\ \[* "$TV_SYM"/"Psych"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Raising\ Hope\ -\ \[*' >/dev/null 2>&1 ; then mv -v Raising\ Hope\ -\ \[* "$TV_SYM"/"Raising Hope"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rake\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Rake\ \(US\)\ -\ \[* "$TV_SYM"/"Rake (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Ray\ Donovan\ -\ \[*' >/dev/null 2>&1 ; then mv -v Ray\ Donovan\ -\ \[* "$TV_SYM"/"Ray Donovan"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rectify\ -\ \[*' >/dev/null 2>&1 ; then mv -v Rectify\ -\ \[* "$TV_SYM"/"Rectify"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Red\ Band\ Society\ -\ \[*' >/dev/null 2>&1 ; then mv -v Red\ Band\ Society\ -\ \[* "$TV_SYM"/"Red Band Society"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Reno\ 911!\ -\ \[*' >/dev/null 2>&1 ; then mv -v Reno\ 911!\ -\ \[* "$TV_SYM"/"Reno 911!"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rescue\ Me\ -\ \[*' >/dev/null 2>&1 ; then mv -v Rescue\ Me\ -\ \[* "$TV_SYM"/"Rescue Me"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Review\ -\ \[*' >/dev/null 2>&1 ; then mv -v Review\ -\ \[* "$TV_SYM"/"Review"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Revolution\ -\ \[*' >/dev/null 2>&1 ; then mv -v Revolution\ -\ \[* "$TV_SYM"/"Revolution"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rizzoli\ \&\ Isles\ -\ \[*' >/dev/null 2>&1 ; then mv -v Rizzoli\ \&\ Isles\ -\ \[* "$TV_SYM"/"Rizzoli & Isles"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Roc\ -\ \[*' >/dev/null 2>&1 ; then mv -v Roc\ -\ \[* "$TV_SYM"/"Roc"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rookie\ Blue\ -\ \[*' >/dev/null 2>&1 ; then mv -v Rookie\ Blue\ -\ \[* "$TV_SYM"/"Rookie Blue"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Royal\ Pains\ -\ \[*' >/dev/null 2>&1 ; then mv -v Royal\ Pains\ -\ \[* "$TV_SYM"/"Royal Pains"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Sabrina\ The\ Teenage\ Witch\ -\ \[*' >/dev/null 2>&1 ; then mv -v Sabrina\ The\ Teenage\ Witch\ -\ \[* "$TV_SYM"/"Sabrina The Teenage Witch"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Saint\ George\ -\ \[*' >/dev/null 2>&1 ; then mv -v Saint\ George\ -\ \[* "$TV_SYM"/"Saint George"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Saved\ by\ the\ Bell\ -\ \[*' >/dev/null 2>&1 ; then mv -v Saved\ by\ the\ Bell\ -\ \[* "$TV_SYM"/"Saved by the Bell"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Saved\ by\ the\ Bell\ The\ College\ Years\ -\ \[*' >/dev/null 2>&1 ; then mv -v Saved\ by\ the\ Bell\ The\ College\ Years\ -\ \[* "$TV_SYM"/"Saved by the Bell The College Years"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Scorpion\ -\ \[*' >/dev/null 2>&1 ; then mv -v Scorpion\ -\ \[* "$TV_SYM"/"Scorpion"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Scrubs\ -\ \[*' >/dev/null 2>&1 ; then mv -v Scrubs\ -\ \[* "$TV_SYM"/"Scrubs"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Seinfeld\ -\ \[*' >/dev/null 2>&1 ; then mv -v Seinfeld\ -\ \[* "$TV_SYM"/"Seinfeld"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Sex\ and\ the\ City\ -\ \[*' >/dev/null 2>&1 ; then mv -v Sex\ and\ the\ City\ -\ \[* "$TV_SYM"/"Sex and the City"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Shark\ Tank\ -\ \[*' >/dev/null 2>&1 ; then mv -v Shark\ Tank\ -\ \[* "$TV_SYM"/"Shark Tank"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Shipping\ Wars\ -\ \[*' >/dev/null 2>&1 ; then mv -v Shipping\ Wars\ -\ \[* "$TV_SYM"/"Shipping Wars"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Silicon\ Valley\ -\ \[*' >/dev/null 2>&1 ; then mv -v Silicon\ Valley\ -\ \[* "$TV_SYM"/"Silicon Valley"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Six\ Feet\ Under\ -\ \[*' >/dev/null 2>&1 ; then mv -v Six\ Feet\ Under\ -\ \[* "$TV_SYM"/"Six Feet Under"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Sleepy\ Hollow\ -\ \[*' >/dev/null 2>&1 ; then mv -v Sleepy\ Hollow\ -\ \[* "$TV_SYM"/"Sleepy Hollow"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Sons\ of\ Anarchy\ -\ \[*' >/dev/null 2>&1 ; then mv -v Sons\ of\ Anarchy\ -\ \[* "$TV_SYM"/"Sons of Anarchy"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Sons\ of\ Guns\ -\ \[*' >/dev/null 2>&1 ; then mv -v Sons\ of\ Guns\ -\ \[* "$TV_SYM"/"Sons of Guns"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'South\ Beach\ Tow\ -\ \[*' >/dev/null 2>&1 ; then mv -v South\ Beach\ Tow\ -\ \[* "$TV_SYM"/"South Beach Tow"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Southland\ -\ \[*' >/dev/null 2>&1 ; then mv -v Southland\ -\ \[* "$TV_SYM"/"Southland"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'South\ Park\ -\ \[*' >/dev/null 2>&1 ; then mv -v South\ Park\ -\ \[* "$TV_SYM"/"South Park"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Spin\ City\ -\ \[*' >/dev/null 2>&1 ; then mv -v Spin\ City\ -\ \[* "$TV_SYM"/"Spin City"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'State\ of\ Affairs\ -\ \[*' >/dev/null 2>&1 ; then mv -v State\ of\ Affairs\ -\ \[* "$TV_SYM"/"State of Affairs"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Still\ Standing\ -\ \[*' >/dev/null 2>&1 ; then mv -v Still\ Standing\ -\ \[* "$TV_SYM"/"Still Standing"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Storage\ Wars\ -\ \[*' >/dev/null 2>&1 ; then mv -v Storage\ Wars\ -\ \[* "$TV_SYM"/"Storage Wars"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Storage\ Wars\ Texas\ -\ \[*' >/dev/null 2>&1 ; then mv -v Storage\ Wars\ Texas\ -\ \[* "$TV_SYM"/"Storage Wars Texas"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Storm\ Chasers\ -\ \[*' >/dev/null 2>&1 ; then mv -v Storm\ Chasers\ -\ \[* "$TV_SYM"/"Storm Chasers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Suits\ -\ \[*' >/dev/null 2>&1 ; then mv -v Suits\ -\ \[* "$TV_SYM"/"Suits"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Super\ Fun\ Night\ -\ \[*' >/dev/null 2>&1 ; then mv -v Super\ Fun\ Night\ -\ \[* "$TV_SYM"/"Super Fun Night"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Surviving\ Jack\ -\ \[*' >/dev/null 2>&1 ; then mv -v Surviving\ Jack\ -\ \[* "$TV_SYM"/"Surviving Jack"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Surviving\ the\ Cut\ -\ \[*' >/dev/null 2>&1 ; then mv -v Surviving\ the\ Cut\ -\ \[* "$TV_SYM"/"Surviving the Cut"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Switched\ at\ Birth\ -\ \[*' >/dev/null 2>&1 ; then mv -v Switched\ at\ Birth\ -\ \[* "$TV_SYM"/"Switched at Birth"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Tanked\ -\ \[*' >/dev/null 2>&1 ; then mv -v Tanked\ -\ \[* "$TV_SYM"/"Tanked"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'That\ 70s\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v That\ 70s\ Show\ -\ \[* "$TV_SYM"/"That 70's Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ 4400\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ 4400\ -\ \[* "$TV_SYM"/"The 4400"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Affair\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Affair\ -\ \[* "$TV_SYM"/"The Affair"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ After\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ After\ -\ \[* "$TV_SYM"/"The After"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Amazing\ Race\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Amazing\ Race\ -\ \[* "$TV_SYM"/"The Amazing Race"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Americans\ \(2013\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Americans\ \(2013\)\ -\ \[* "$TV_SYM"/"The Americans (2013)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Awesomes\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Awesomes\ -\ \[* "$TV_SYM"/"The Awesomes"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Bernie\ Mac\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Bernie\ Mac\ Show\ -\ \[* "$TV_SYM"/"The Bernie Mac Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Beverly\ Hillbillies\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Beverly\ Hillbillies\ -\ \[* "$TV_SYM"/"The Beverly Hillbillies"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Big\ Bang\ Theory\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Big\ Bang\ Theory\ -\ \[* "$TV_SYM"/"The Big Bang Theory"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Blacklist\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Blacklist\ -\ \[* "$TV_SYM"/"The Blacklist"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Border\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Border\ -\ \[* "$TV_SYM"/"The Border"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Bridge\ \(2013\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Bridge\ \(2013\)\ -\ \[* "$TV_SYM"/"The Bridge (2013)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Cleveland\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Cleveland\ Show\ -\ \[* "$TV_SYM"/"The Cleveland Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Colony\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Colony\ -\ \[* "$TV_SYM"/"The Colony"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Crazy\ Ones\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Crazy\ Ones\ -\ \[* "$TV_SYM"/"The Crazy Ones"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Dead\ Zone\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Dead\ Zone\ -\ \[* "$TV_SYM"/"The Dead Zone"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Flash\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Flash\ -\ \[* "$TV_SYM"/"The Flash"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Flash\ \(2014\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Flash\ \(2014\)\ -\ \[* "$TV_SYM"/"The Flash (2014)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Following\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Following\ -\ \[* "$TV_SYM"/"The Following"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Fresh\ Prince\ of\ Bel-Air\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Fresh\ Prince\ of\ Bel-Air\ -\ \[* "$TV_SYM"/"The Fresh Prince of Bel-Air"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Goldbergs\ \(2013\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Goldbergs\ \(2013\)\ -\ \[* "$TV_SYM"/"The Goldbergs (2013)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Good\ Wife\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Good\ Wife\ -\ \[* "$TV_SYM"/"The Good Wife"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Goodwin\ Games\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Goodwin\ Games\ -\ \[* "$TV_SYM"/"The Goodwin Games"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Inbetweeners\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Inbetweeners\ \(US\)\ -\ \[* "$TV_SYM"/"The Inbetweeners (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ King\ of\ Queens\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ King\ of\ Queens\ -\ \[* "$TV_SYM"/"The King of Queens"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Last\ Ship\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Last\ Ship\ -\ \[* "$TV_SYM"/"The Last Ship"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ League\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ League\ -\ \[* "$TV_SYM"/"The League"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Leftovers\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Leftovers\ -\ \[* "$TV_SYM"/"The Leftovers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Lottery\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Lottery\ -\ \[* "$TV_SYM"/"The Lottery"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Mentalist\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Mentalist\ -\ \[* "$TV_SYM"/"The Mentalist"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Michael\ J.\ Fox\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Michael\ J.\ Fox\ Show\ -\ \[* "$TV_SYM"/"The Michael J. Fox Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Middle\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Middle\ -\ \[* "$TV_SYM"/"The Middle"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Millers\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Millers\ -\ \[* "$TV_SYM"/"The Millers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Mysteries\ of\ Laura\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Mysteries\ of\ Laura\ -\ \[* "$TV_SYM"/"The Mysteries of Laura"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Neighbors\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Neighbors\ -\ \[* "$TV_SYM"/"The Neighbors"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Night\ Shift\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Night\ Shift\ -\ \[* "$TV_SYM"/"The Night Shift"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Office\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Office\ \(US\)\ -\ \[* "$TV_SYM"/"The Office (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Rebels\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Rebels\ -\ \[* "$TV_SYM"/"The Rebels"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Shield\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Shield\ -\ \[* "$TV_SYM"/"The Shield"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Simpsons\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Simpsons\ -\ \[* "$TV_SYM"/"The Simpsons"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Sopranos\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Sopranos\ -\ \[* "$TV_SYM"/"The Sopranos"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Tomorrow\ People\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Tomorrow\ People\ \(US\)\ -\ \[* "$TV_SYM"/"The Tomorrow People (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Unit\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Unit\ -\ \[* "$TV_SYM"/"The Unit"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Walking\ Dead\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Walking\ Dead\ -\ \[* "$TV_SYM"/"The Walking Dead"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ West\ Wing\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ West\ Wing\ -\ \[* "$TV_SYM"/"The West Wing"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Wire\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Wire\ -\ \[* "$TV_SYM"/"The Wire"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Third\ Watch\ -\ \[*' >/dev/null 2>&1 ; then mv -v Third\ Watch\ -\ \[* "$TV_SYM"/"Third Watch"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Time\ Warp\ -\ \[*' >/dev/null 2>&1 ; then mv -v Time\ Warp\ -\ \[* "$TV_SYM"/"Time Warp"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Top\ 20\ Most\ Shocking\ -\ \[*' >/dev/null 2>&1 ; then mv -v Top\ 20\ Most\ Shocking\ -\ \[* "$TV_SYM"/"Top 20 Most Shocking"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Top\ Shot\ -\ \[*' >/dev/null 2>&1 ; then mv -v Top\ Shot\ -\ \[* "$TV_SYM"/"Top Shot"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Touch\ \(2012\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Touch\ \(2012\)\ -\ \[* "$TV_SYM"/"Touch (2012)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Transparent\ -\ \[*' >/dev/null 2>&1 ; then mv -v Transparent\ -\ \[* "$TV_SYM"/"Transparent"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Trophy\ Wife\ -\ \[*' >/dev/null 2>&1 ; then mv -v Trophy\ Wife\ -\ \[* "$TV_SYM"/"Trophy Wife"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'True\ Detective\ -\ \[*' >/dev/null 2>&1 ; then mv -v True\ Detective\ -\ \[* "$TV_SYM"/"True Detective"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Two\ and\ a\ Half\ Men\ -\ \[*' >/dev/null 2>&1 ; then mv -v Two\ and\ a\ Half\ Men\ -\ \[* "$TV_SYM"/"Two and a Half Men"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Tyrant\ -\ \[*' >/dev/null 2>&1 ; then mv -v Tyrant\ -\ \[* "$TV_SYM"/"Tyrant"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Undateable\ \(2014\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Undateable\ \(2014\)\ -\ \[* "$TV_SYM"/"Undateable (2014)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Under\ the\ Dome\ -\ \[*' >/dev/null 2>&1 ; then mv -v Under\ the\ Dome\ -\ \[* "$TV_SYM"/"Under the Dome"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Unforgettable\ -\ \[*' >/dev/null 2>&1 ; then mv -v Unforgettable\ -\ \[* "$TV_SYM"/"Unforgettable"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Utopia\ \(US\)\ \(2014\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Utopia\ \(US\)\ \(2014\)\ -\ \[* "$TV_SYM"/"Utopia (US) (2014)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Veep\ -\ \[*' >/dev/null 2>&1 ; then mv -v Veep\ -\ \[* "$TV_SYM"/"Veep"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Vegas\ Strip\ -\ \[*' >/dev/null 2>&1 ; then mv -v Vegas\ Strip\ -\ \[* "$TV_SYM"/"Vegas Strip"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'VICE\ -\ \[*' >/dev/null 2>&1 ; then mv -v VICE\ -\ \[* "$TV_SYM"/"VICE"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Walker,\ Texas\ Ranger\ -\ \[*' >/dev/null 2>&1 ; then mv -v Walker,\ Texas\ Ranger\ -\ \[* "$TV_SYM"/"Walker, Texas Ranger"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Weeds\ -\ \[*' >/dev/null 2>&1 ; then mv -v Weeds\ -\ \[* "$TV_SYM"/"Weeds"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'White\ Collar\ -\ \[*' >/dev/null 2>&1 ; then mv -v White\ Collar\ -\ \[* "$TV_SYM"/"White Collar"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Wilfred\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Wilfred\ \(US\)\ -\ \[* "$TV_SYM"/"Wilfred (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Wipeout\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v Wipeout\ \(US\)\ -\ \[* "$TV_SYM"/"Wipeout (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Without\ a\ Trace\ -\ \[*' >/dev/null 2>&1 ; then mv -v Without\ a\ Trace\ -\ \[* "$TV_SYM"/"Without a Trace"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Workaholics\ -\ \[*' >/dev/null 2>&1 ; then mv -v Workaholics\ -\ \[* "$TV_SYM"/"Workaholics"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Young\ \&\ Hungry\ -\ \[*' >/dev/null 2>&1 ; then mv -v Young\ \&\ Hungry\ -\ \[* "$TV_SYM"/"Young & Hungry"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Will\ \&\ Grace\ -\ \[*' >/dev/null 2>&1 ; then mv -v Will\ \&\ Grace\ -\ \[* "$TV_SYM"/"Will & Grace"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Martin\ -\ \[*' >/dev/null 2>&1 ; then mv -v Martin\ -\ \[* "$TV_SYM"/"Martin"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'MASH\ -\ \[*' >/dev/null 2>&1 ; then mv -v MASH\ -\ \[* "$TV_SYM"/"MASH"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Martin\ -\ \[*' >/dev/null 2>&1 ; then mv -v Martin\ -\ \[* "$TV_SYM"/"Martin"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Wings\ -\ \[*' >/dev/null 2>&1 ; then mv -v Wings\ -\ \[* "$TV_SYM"/"Wings"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Murphy\ Brown\ -\ \[*' >/dev/null 2>&1 ; then mv -v Murphy\ Brown\ -\ \[* "$TV_SYM"/"Murphy Brown"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Drew\ Carey\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Drew\ Carey\ Show\ -\ \[* "$TV_SYM"/"The Drew Carey Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Family\ Matters\ -\ \[*' >/dev/null 2>&1 ; then mv -v Family\ Matters\ -\ \[* "$TV_SYM"/"Family Matters"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mad\ About\ You\ -\ \[*' >/dev/null 2>&1 ; then mv -v Mad\ About\ You\ -\ \[* "$TV_SYM"/"Mad About You"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Picket\ Fences\ -\ \[*' >/dev/null 2>&1 ; then mv -v Picket\ Fences\ -\ \[* "$TV_SYM"/"Picket Fences"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chicago\ Hope\ -\ \[*' >/dev/null 2>&1 ; then mv -v Chicago\ Hope\ -\ \[* "$TV_SYM"/"Chicago Hope"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Ellen\ -\ \[*' >/dev/null 2>&1 ; then mv -v Ellen\ -\ \[* "$TV_SYM"/"Ellen"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'In\ Living\ Color\ -\ \[*' >/dev/null 2>&1 ; then mv -v In\ Living\ Color\ -\ \[* "$TV_SYM"/"In Living Color"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Grace\ Under\ Fire\ -\ \[*' >/dev/null 2>&1 ; then mv -v Grace\ Under\ Fire\ -\ \[* "$TV_SYM"/"Grace Under Fire"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Roseanne\ -\ \[*' >/dev/null 2>&1 ; then mv -v Roseanne\ -\ \[* "$TV_SYM"/"Roseanne"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ X-Files\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ X-Files\ -\ \[* "$TV_SYM"/"The X-Files"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Ally\ McBeal\ -\ \[*' >/dev/null 2>&1 ; then mv -v Ally\ McBeal\ -\ \[* "$TV_SYM"/"Ally McBeal"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Six\ Million\ Dollar\ Man\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Six\ Million\ Dollar\ Man\ -\ \[* "$TV_SYM"/"The Six Million Dollar Man"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mission\ Impossible\ -\ \[*' >/dev/null 2>&1 ; then mv -v Mission\ Impossible\ -\ \[* "$TV_SYM"/"Mission: Impossible"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Doogie\ Howser,\ M.D.\ -\ \[*' >/dev/null 2>&1 ; then mv -v Doogie\ Howser,\ M.D.\ -\ \[* "$TV_SYM"/"Doogie Howser, M.D."/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Perfect\ Strangers\ -\ \[*' >/dev/null 2>&1 ; then mv -v Perfect\ Strangers\ -\ \[* "$TV_SYM"/"Perfect Strangers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Kojak\ -\ \[*' >/dev/null 2>&1 ; then mv -v Kojak\ -\ \[* "$TV_SYM"/"Kojak"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Get\ Smart\ -\ \[*' >/dev/null 2>&1 ; then mv -v Get\ Smart\ -\ \[* "$TV_SYM"/"Get Smart"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'T.J.\ Hooker\ -\ \[*' >/dev/null 2>&1 ; then mv -v T.J.\ Hooker\ -\ \[* "$TV_SYM"/"T.J. Hooker"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Odd\ Couple\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Odd\ Couple\ -\ \[* "$TV_SYM"/"The Odd Couple"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Sanford\ and\ Son\ -\ \[*' >/dev/null 2>&1 ; then mv -v Sanford\ and\ Son\ -\ \[* "$TV_SYM"/"Sanford and Son"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'L.A.\ Law\ -\ \[*' >/dev/null 2>&1 ; then mv -v L.A.\ Law\ -\ \[* "$TV_SYM"/"L.A. Law"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Knight\ Rider\ -\ \[*' >/dev/null 2>&1 ; then mv -v Knight\ Rider\ -\ \[* "$TV_SYM"/"Knight Rider"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Baywatch\ -\ \[*' >/dev/null 2>&1 ; then mv -v Baywatch\ -\ \[* "$TV_SYM"/"Baywatch"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Miami\ Vice\ -\ \[*' >/dev/null 2>&1 ; then mv -v Miami\ Vice\ -\ \[* "$TV_SYM"/"Miami Vice"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Facts\ of\ Life\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Facts\ of\ Life\ -\ \[* "$TV_SYM"/"The Facts of Life"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Family\ Ties\ -\ \[*' >/dev/null 2>&1 ; then mv -v Family\ Ties\ -\ \[* "$TV_SYM"/"Family Ties"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Matlock\ -\ \[*' >/dev/null 2>&1 ; then mv -v Matlock\ -\ \[* "$TV_SYM"/"Matlock"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Diffrent\ Strokes\ -\ \[*' >/dev/null 2>&1 ; then mv -v Diffrent\ Strokes\ -\ \[* "$TV_SYM"/"Diff'rent Strokes"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E '21\ Jump\ Street\ -\ \[*' >/dev/null 2>&1 ; then mv -v 21\ Jump\ Street\ -\ \[* "$TV_SYM"/"21 Jump Street"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ A-Team\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ A-Team\ -\ \[* "$TV_SYM"/"The A-Team"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Magnum,\ P.I.\ -\ \[*' >/dev/null 2>&1 ; then mv -v Magnum,\ P.I.\ -\ \[* "$TV_SYM"/"Magnum, P.I."/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Golden\ Girls\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Golden\ Girls\ -\ \[* "$TV_SYM"/"The Golden Girls"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Brady\ Bunch\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Brady\ Bunch\ -\ \[* "$TV_SYM"/"The Brady Bunch"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bonanza\ -\ \[*' >/dev/null 2>&1 ; then mv -v Bonanza\ -\ \[* "$TV_SYM"/"Bonanza"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Threes\ Company\ -\ \[*' >/dev/null 2>&1 ; then mv -v Threes\ Company\ -\ \[* "$TV_SYM"/"Three's Company"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hawaii\ Five-O\ -\ \[*' >/dev/null 2>&1 ; then mv -v Hawaii\ Five-O\ -\ \[* "$TV_SYM"/"Hawaii Five-O"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Cheers\ -\ \[*' >/dev/null 2>&1 ; then mv -v Cheers\ -\ \[* "$TV_SYM"/"Cheers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Cosby\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Cosby\ Show\ -\ \[* "$TV_SYM"/"The Cosby Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Dukes\ of\ Hazzard\ -\ \[*' >/dev/null 2>&1 ; then mv -v The\ Dukes\ of\ Hazzard\ -\ \[* "$TV_SYM"/"The Dukes of Hazzard"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
