#!/bin/bash
# Move episodes to their folders
SCRIPT_NAME="move"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


RED


echo -e "
--------------------------------------------------------------
               Starting File Transfer
--------------------------------------------------------------
"


CYAN

#if [ -f "/media/{"/2 TB"/,"/TB 7"/Downloads}/{Finished,Finished/*}/                "$TV_SYM"/""/ 2>/dev/null && echo -e "nn"

#Run Duplicate Number Generator
RANDOM_NUMBER_GENERATOR

#echo "Fixing Subtitles, If there are any!"
#sed -i '/Subtitles downloaded from www.OpenSubtitles.org/d;/Best watched using Open Subtitles MKV Player/d' *.srt 2>/dev/null
echo""

if [ "$find_missing_file_move" = "Y" ]
then TV_SYM="$TMP_D/Shows"
else TV_SYM="$TV_SYM"
fi


if ls -U | grep -E 'About\ a\ Boy\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" About\ a\ Boy\ -\ \[* "$TV_SYM"/"About a Boy"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'American\ Dad!\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" American\ Dad!\ -\ \[* "$TV_SYM"/"American Dad!"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Angie\ Tribeca\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Angie\ Tribeca\ -\ \[* "$TV_SYM"/"Angie Tribeca"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Archer\ \(2009\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Archer\ \(2009\)\ -\ \[* "$TV_SYM"/"Archer (2009)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Arrested\ Development\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Arrested\ Development\ -\ \[* "$TV_SYM"/"Arrested Development"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Arrow\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Arrow\ -\ \[* "$TV_SYM"/"Arrow"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Becker\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Becker\ -\ \[* "$TV_SYM"/"Becker"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Better\ Call\ Saul\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Better\ Call\ Saul\ -\ \[* "$TV_SYM"/"Better Call Saul"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Billions\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Billions\ -\ \[* "$TV_SYM"/"Billions"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Black-ish\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Black-ish\ -\ \[* "$TV_SYM"/"Black-ish"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Blindspot\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Blindspot\ -\ \[* "$TV_SYM"/"Blindspot"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bloodline\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Bloodline\ -\ \[* "$TV_SYM"/"Bloodline"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Blue\ Bloods\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Blue\ Bloods\ -\ \[* "$TV_SYM"/"Blue Bloods"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bobs\ Burgers\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Bobs\ Burgers\ -\ \[* "$TV_SYM"/"Bob's Burgers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Body\ of\ Proof\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Body\ of\ Proof\ -\ \[* "$TV_SYM"/"Body of Proof"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bonanza\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Bonanza\ -\ \[* "$TV_SYM"/"Bonanza"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Bosch\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Bosch\ -\ \[* "$TV_SYM"/"Bosch"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Boston\ Legal\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Boston\ Legal\ -\ \[* "$TV_SYM"/"Boston Legal"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Breaking\ Bad\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Breaking\ Bad\ -\ \[* "$TV_SYM"/"Breaking Bad"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Brooklyn\ Nine-Nine\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Brooklyn\ Nine-Nine\ -\ \[* "$TV_SYM"/"Brooklyn Nine-Nine"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Castle\ \(2009\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Castle\ \(2009\)\ -\ \[* "$TV_SYM"/"Castle (2009)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Casual\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Casual\ -\ \[* "$TV_SYM"/"Casual"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chicago\ Fire\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Chicago\ Fire\ -\ \[* "$TV_SYM"/"Chicago Fire"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chicago\ Hope\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Chicago\ Hope\ -\ \[* "$TV_SYM"/"Chicago Hope"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chicago\ Med\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Chicago\ Med\ -\ \[* "$TV_SYM"/"Chicago Med"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Chicago\ P.D.\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Chicago\ P.D.\ -\ \[* "$TV_SYM"/"Chicago P.D."/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Coach\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Coach\ -\ \[* "$TV_SYM"/"Coach"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Cold\ Case\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Cold\ Case\ -\ \[* "$TV_SYM"/"Cold Case"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Colony\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Colony\ -\ \[* "$TV_SYM"/"Colony"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Covert\ Affairs\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Covert\ Affairs\ -\ \[* "$TV_SYM"/"Covert Affairs"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Crazy\ Ex-Girlfriend\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Crazy\ Ex-Girlfriend\ -\ \[* "$TV_SYM"/"Crazy Ex-Girlfriend"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Criminal\ Minds\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Criminal\ Minds\ -\ \[* "$TV_SYM"/"Criminal Minds"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Crossing\ Lines\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Crossing\ Lines\ -\ \[* "$TV_SYM"/"Crossing Lines"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'CSI\ Crime\ Scene\ Investigation\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" CSI\ Crime\ Scene\ Investigation\ -\ \[* "$TV_SYM"/"CSI Crime Scene Investigation"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'CSI\ Miami\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" CSI\ Miami\ -\ \[* "$TV_SYM"/"CSI Miami"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'CSINY\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" CSINY\ -\ \[* "$TV_SYM"/"CSINY"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Dallas\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Dallas\ -\ \[* "$TV_SYM"/"Dallas"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Damages\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Damages\ -\ \[* "$TV_SYM"/"Damages"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Deadbeat\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Deadbeat\ -\ \[* "$TV_SYM"/"Deadbeat"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Dr.\ Ken\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Dr.\ Ken\ -\ \[* "$TV_SYM"/"Dr. Ken"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Eastbound\ \&\ Down\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Eastbound\ \&\ Down\ -\ \[* "$TV_SYM"/"Eastbound & Down"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Ellen\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Ellen\ -\ \[* "$TV_SYM"/"Ellen"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Entourage\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Entourage\ -\ \[* "$TV_SYM"/"Entourage"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Everybody\ Loves\ Raymond\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Everybody\ Loves\ Raymond\ -\ \[* "$TV_SYM"/"Everybody Loves Raymond"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Falling\ Skies\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Falling\ Skies\ -\ \[* "$TV_SYM"/"Falling Skies"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Family\ Guy\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Family\ Guy\ -\ \[* "$TV_SYM"/"Family Guy"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Fargo\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Fargo\ -\ \[* "$TV_SYM"/"Fargo"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'F\ is\ for\ Family\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" F\ is\ for\ Family\ -\ \[* "$TV_SYM"/"F is for Family"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Flashpoint\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Flashpoint\ -\ \[* "$TV_SYM"/"Flashpoint"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Franklin\ \&\ Bash\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Franklin\ \&\ Bash\ -\ \[* "$TV_SYM"/"Franklin & Bash"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Friends\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Friends\ -\ \[* "$TV_SYM"/"Friends"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Game\ of\ Thrones\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Game\ of\ Thrones\ -\ \[* "$TV_SYM"/"Game of Thrones"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Get\ Smart\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Get\ Smart\ -\ \[* "$TV_SYM"/"Get Smart"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Getting\ On\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Getting\ On\ \(US\)\ -\ \[* "$TV_SYM"/"Getting On (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Gilligans\ Island\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Gilligans\ Island\ -\ \[* "$TV_SYM"/"Gilligan's Island"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Gotham\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Gotham\ -\ \[* "$TV_SYM"/"Gotham"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Graceland\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Graceland\ -\ \[* "$TV_SYM"/"Graceland"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Grace\ Under\ Fire\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Grace\ Under\ Fire\ -\ \[* "$TV_SYM"/"Grace Under Fire"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Grandfathered\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Grandfathered\ -\ \[* "$TV_SYM"/"Grandfathered"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hand\ of\ God\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Hand\ of\ God\ -\ \[* "$TV_SYM"/"Hand of God"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Happy\ Endings\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Happy\ Endings\ -\ \[* "$TV_SYM"/"Happy Endings"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hawaii\ Five-0\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Hawaii\ Five-0\ -\ \[* "$TV_SYM"/"Hawaii Five-0"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hawaii\ Five-O\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Hawaii\ Five-O\ -\ \[* "$TV_SYM"/"Hawaii Five-O"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hell\ on\ Wheels\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Hell\ on\ Wheels\ -\ \[* "$TV_SYM"/"Hell on Wheels"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Hill\ Street\ Blues\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Hill\ Street\ Blues\ -\ \[* "$TV_SYM"/"Hill Street Blues"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'House\ of\ Cards\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" House\ of\ Cards\ \(US\)\ -\ \[* "$TV_SYM"/"House of Cards (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'House\ of\ Lies\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" House\ of\ Lies\ -\ \[* "$TV_SYM"/"House of Lies"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'How\ to\ Get\ Away\ with\ Murder\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" How\ to\ Get\ Away\ with\ Murder\ -\ \[* "$TV_SYM"/"How to Get Away with Murder"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'In\ Living\ Color\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" In\ Living\ Color\ -\ \[* "$TV_SYM"/"In Living Color"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Into\ the\ Badlands\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Into\ the\ Badlands\ -\ \[* "$TV_SYM"/"Into the Badlands"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'JAG\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" JAG\ -\ \[* "$TV_SYM"/"JAG"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Justified\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Justified\ -\ \[* "$TV_SYM"/"Justified"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Just\ Shoot\ Me\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Just\ Shoot\ Me\ -\ \[* "$TV_SYM"/"Just Shoot Me"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Knight\ Rider\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Knight\ Rider\ -\ \[* "$TV_SYM"/"Knight Rider"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Kroll\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Kroll\ Show\ -\ \[* "$TV_SYM"/"Kroll Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'L.A.\ Law\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" L.A.\ Law\ -\ \[* "$TV_SYM"/"L.A. Law"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Law\ \&\ Order\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Law\ \&\ Order\ -\ \[* "$TV_SYM"/"Law & Order"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Law\ \&\ Order\ Criminal\ Intent\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Law\ \&\ Order\ Criminal\ Intent\ -\ \[* "$TV_SYM"/"Law & Order: Criminal Intent"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Law\ \&\ Order\ Special\ Victims\ Unit\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Law\ \&\ Order\ Special\ Victims\ Unit\ -\ \[* "$TV_SYM"/"Law & Order: Special Victims Unit"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Lie\ to\ me\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Lie\ to\ me\ -\ \[* "$TV_SYM"/"Lie to me"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Life\ \(2007\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Life\ \(2007\)\ -\ \[* "$TV_SYM"/"Life (2007)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Life\ in\ Pieces\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Life\ in\ Pieces\ -\ \[* "$TV_SYM"/"Life in Pieces"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'MacGyver\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" MacGyver\ -\ \[* "$TV_SYM"/"MacGyver"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Madam\ Secretary\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Madam\ Secretary\ -\ \[* "$TV_SYM"/"Madam Secretary"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mad\ Men\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Mad\ Men\ -\ \[* "$TV_SYM"/"Mad Men"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Magnum,\ P.I.\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Magnum,\ P.I.\ -\ \[* "$TV_SYM"/"Magnum, P.I."/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Man\ Finds\ Food\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Man\ Finds\ Food\ -\ \[* "$TV_SYM"/"Man Finds Food"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Martin\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Martin\ -\ \[* "$TV_SYM"/"Martin"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E '*S.H.I.E.L.D*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Marvel\'s\ Agents\ of\ S.H.I.E.L.D.\ -\ \[* "$TV_SYM"/"Marvel's Agents of S.H.I.E.L.D."/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Marvels\ Agents\ of\ S.H.I.E.L.D.\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Marvel\'s\ Agents\ of\ S.H.I.E.L.D.\ -\ \[* "$TV_SYM"/"Marvel's Agents of S.H.I.E.L.D."/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'MASH\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" MASH\ -\ \[* "$TV_SYM"/"MASH"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Matlock\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Matlock\ -\ \[* "$TV_SYM"/"Matlock"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Miami\ Vice\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Miami\ Vice\ -\ \[* "$TV_SYM"/"Miami Vice"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mission\ Impossible\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Mission\ Impossible\ -\ \[* "$TV_SYM"/"Mission: Impossible"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Modern\ Family\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Modern\ Family\ -\ \[* "$TV_SYM"/"Modern Family"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mom\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Mom\ -\ \[* "$TV_SYM"/"Mom"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Mr.\ Robot\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Mr.\ Robot\ -\ \[* "$TV_SYM"/"Mr. Robot"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Narcos\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Narcos\ -\ \[* "$TV_SYM"/"Narcos"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'NCIS\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" NCIS\ -\ \[* "$TV_SYM"/"NCIS"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'NCIS\ Los\ Angeles\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" NCIS\ Los\ Angeles\ -\ \[* "$TV_SYM"/"NCIS Los Angeles"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'NYPD\ Blue\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" NYPD\ Blue\ -\ \[* "$TV_SYM"/"NYPD Blue"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Odd\ Mom\ Out\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Odd\ Mom\ Out\ -\ \[* "$TV_SYM"/"Odd Mom Out"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Orange\ Is\ the\ New\ Black\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Orange\ Is\ the\ New\ Black\ -\ \[* "$TV_SYM"/"Orange Is the New Black"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Oz\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Oz\ -\ \[* "$TV_SYM"/"Oz"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Parenthood\ \(2010\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Parenthood\ \(2010\)\ -\ \[* "$TV_SYM"/"Parenthood (2010)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Parks\ and\ Recreation\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Parks\ and\ Recreation\ -\ \[* "$TV_SYM"/"Parks and Recreation"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Person\ of\ Interest\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Person\ of\ Interest\ -\ \[* "$TV_SYM"/"Person of Interest"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Picket\ Fences\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Picket\ Fences\ -\ \[* "$TV_SYM"/"Picket Fences"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Playing\ House\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Playing\ House\ -\ \[* "$TV_SYM"/"Playing House"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Preacher\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Preacher\ -\ \[* "$TV_SYM"/"Preacher"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Psych\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Psych\ -\ \[* "$TV_SYM"/"Psych"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Quantico\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Quantico\ -\ \[* "$TV_SYM"/"Quantico"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Raising\ Hope\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Raising\ Hope\ -\ \[* "$TV_SYM"/"Raising Hope"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Ray\ Donovan\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Ray\ Donovan\ -\ \[* "$TV_SYM"/"Ray Donovan"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rectify\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Rectify\ -\ \[* "$TV_SYM"/"Rectify"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Remington\ Steele\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Remington\ Steele\ -\ \[* "$TV_SYM"/"Remington Steele"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rescue\ Me\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Rescue\ Me\ -\ \[* "$TV_SYM"/"Rescue Me"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Revolution\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Revolution\ -\ \[* "$TV_SYM"/"Revolution"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rick\ and\ Morty\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Rick\ and\ Morty\ -\ \[* "$TV_SYM"/"Rick and Morty"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rizzoli\ \&\ Isles\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Rizzoli\ \&\ Isles\ -\ \[* "$TV_SYM"/"Rizzoli & Isles"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rookie\ Blue\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Rookie\ Blue\ -\ \[* "$TV_SYM"/"Rookie Blue"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rosewood\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Rosewood\ -\ \[* "$TV_SYM"/"Rosewood"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Royal\ Pains\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Royal\ Pains\ -\ \[* "$TV_SYM"/"Royal Pains"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Rush\ Hour\ \(2016\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Rush\ Hour\ \(2016\)\ -\ \[* "$TV_SYM"/"Rush Hour (2016)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Scorpion\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Scorpion\ -\ \[* "$TV_SYM"/"Scorpion"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Scrubs\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Scrubs\ -\ \[* "$TV_SYM"/"Scrubs"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Seinfeld\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Seinfeld\ -\ \[* "$TV_SYM"/"Seinfeld"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Sense8\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Sense8\ -\ \[* "$TV_SYM"/"Sense8"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Shades\ of\ Blue\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Shades\ of\ Blue\ -\ \[* "$TV_SYM"/"Shades of Blue"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Silicon\ Valley\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Silicon\ Valley\ -\ \[* "$TV_SYM"/"Silicon Valley"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Six\ Feet\ Under\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Six\ Feet\ Under\ -\ \[* "$TV_SYM"/"Six Feet Under"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Sleepy\ Hollow\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Sleepy\ Hollow\ -\ \[* "$TV_SYM"/"Sleepy Hollow"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Southland\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Southland\ -\ \[* "$TV_SYM"/"Southland"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'South\ Park\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" South\ Park\ -\ \[* "$TV_SYM"/"South Park"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Spin\ City\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Spin\ City\ -\ \[* "$TV_SYM"/"Spin City"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Suits\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Suits\ -\ \[* "$TV_SYM"/"Suits"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Supergirl\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Supergirl\ -\ \[* "$TV_SYM"/"Supergirl"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Superstore\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Superstore\ -\ \[* "$TV_SYM"/"Superstore"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'That\ 70s\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" That\ 70s\ Show\ -\ \[* "$TV_SYM"/"That 70's Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ 4400\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ 4400\ -\ \[* "$TV_SYM"/"The 4400"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Affair\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Affair\ -\ \[* "$TV_SYM"/"The Affair"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Americans\ \(2013\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Americans\ \(2013\)\ -\ \[* "$TV_SYM"/"The Americans (2013)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ A-Team\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ A-Team\ -\ \[* "$TV_SYM"/"The A-Team"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Bernie\ Mac\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Bernie\ Mac\ Show\ -\ \[* "$TV_SYM"/"The Bernie Mac Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Beverly\ Hillbillies\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Beverly\ Hillbillies\ -\ \[* "$TV_SYM"/"The Beverly Hillbillies"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Big\ Bang\ Theory\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Big\ Bang\ Theory\ -\ \[* "$TV_SYM"/"The Big Bang Theory"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Blacklist\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Blacklist\ -\ \[* "$TV_SYM"/"The Blacklist"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Carmichael\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Carmichael\ Show\ -\ \[* "$TV_SYM"/"The Carmichael Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Dead\ Zone\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Dead\ Zone\ -\ \[* "$TV_SYM"/"The Dead Zone"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Drew\ Carey\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Drew\ Carey\ Show\ -\ \[* "$TV_SYM"/"The Drew Carey Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Dukes\ of\ Hazzard\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Dukes\ of\ Hazzard\ -\ \[* "$TV_SYM"/"The Dukes of Hazzard"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Flash\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Flash\ -\ \[* "$TV_SYM"/"The Flash"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Flash\ \(2014\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Flash\ \(2014\)\ -\ \[* "$TV_SYM"/"The Flash (2014)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Following\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Following\ -\ \[* "$TV_SYM"/"The Following"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Goldbergs\ \(2013\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Goldbergs\ \(2013\)\ -\ \[* "$TV_SYM"/"The Goldbergs (2013)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Jim\ Gaffigan\ Show\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Jim\ Gaffigan\ Show\ -\ \[* "$TV_SYM"/"The Jim Gaffigan Show"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Last\ Ship\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Last\ Ship\ -\ \[* "$TV_SYM"/"The Last Ship"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Leftovers\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Leftovers\ -\ \[* "$TV_SYM"/"The Leftovers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Mentalist\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Mentalist\ -\ \[* "$TV_SYM"/"The Mentalist"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Millers\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Millers\ -\ \[* "$TV_SYM"/"The Millers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Mysteries\ of\ Laura\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Mysteries\ of\ Laura\ -\ \[* "$TV_SYM"/"The Mysteries of Laura"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Neighbors\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Neighbors\ -\ \[* "$TV_SYM"/"The Neighbors"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Night\ Shift\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Night\ Shift\ -\ \[* "$TV_SYM"/"The Night Shift"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Odd\ Couple\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Odd\ Couple\ -\ \[* "$TV_SYM"/"The Odd Couple"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Office\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Office\ \(US\)\ -\ \[* "$TV_SYM"/"The Office (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Simpsons\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Simpsons\ -\ \[* "$TV_SYM"/"The Simpsons"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Six\ Million\ Dollar\ Man\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Six\ Million\ Dollar\ Man\ -\ \[* "$TV_SYM"/"The Six Million Dollar Man"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Walking\ Dead\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Walking\ Dead\ -\ \[* "$TV_SYM"/"The Walking Dead"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ West\ Wing\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ West\ Wing\ -\ \[* "$TV_SYM"/"The West Wing"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'T.J.\ Hooker\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" T.J.\ Hooker\ -\ \[* "$TV_SYM"/"T.J. Hooker"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Transparent\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Transparent\ -\ \[* "$TV_SYM"/"Transparent"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Tyrant\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Tyrant\ -\ \[* "$TV_SYM"/"Tyrant"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Unbreakable\ Kimmy\ Schmidt\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Unbreakable\ Kimmy\ Schmidt\ -\ \[* "$TV_SYM"/"Unbreakable Kimmy Schmidt"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Under\ the\ Dome\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Under\ the\ Dome\ -\ \[* "$TV_SYM"/"Under the Dome"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Unforgettable\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Unforgettable\ -\ \[* "$TV_SYM"/"Unforgettable"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Veep\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Veep\ -\ \[* "$TV_SYM"/"Veep"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Walker,\ Texas\ Ranger\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Walker,\ Texas\ Ranger\ -\ \[* "$TV_SYM"/"Walker, Texas Ranger"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Weeds\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Weeds\ -\ \[* "$TV_SYM"/"Weeds"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'White\ Collar\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" White\ Collar\ -\ \[* "$TV_SYM"/"White Collar"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Will\ \&\ Grace\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Will\ \&\ Grace\ -\ \[* "$TV_SYM"/"Will & Grace"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Wings\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Wings\ -\ \[* "$TV_SYM"/"Wings"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Without\ a\ Trace\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Without\ a\ Trace\ -\ \[* "$TV_SYM"/"Without a Trace"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Young\ \&\ Hungry\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Young\ \&\ Hungry\ -\ \[* "$TV_SYM"/"Young & Hungry"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Zoo\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Zoo\ -\ \[* "$TV_SYM"/"Zoo"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Zorro\ \(1957\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Zorro\ \(1957\)\ -\ \[* "$TV_SYM"/"Zorro (1957)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Odd\ Couple\ \(2015\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Odd\ Couple\ \(2015\)\ -\ \[* "$TV_SYM"/"The Odd Couple (2015)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Secret\ Eats\ with\ Adam\ Richman\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Secret\ Eats\ with\ Adam\ Richman\ -\ \[* "$TV_SYM"/"Secret Eats with Adam Richman"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Shameless\ \(US\)\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Shameless\ \(US\)\ -\ \[* "$TV_SYM"/"Shameless (US)"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Fresh\ Off\ the\ Boat\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Fresh\ Off\ the\ Boat\ -\ \[* "$TV_SYM"/"Fresh Off the Boat"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Westworld\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Westworld\ -\ \[* "$TV_SYM"/"Westworld"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Man\ Seeking\ Woman\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Man\ Seeking\ Woman\ -\ \[* "$TV_SYM"/"Man Seeking Woman"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Master\ Of\ None\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Master\ Of\ None\ -\ \[* "$TV_SYM"/"Master Of None"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Knick\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Knick\ -\ \[* "$TV_SYM"/"The Knick"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'The\ Leftovers\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" The\ Leftovers\ -\ \[* "$TV_SYM"/"The Leftovers"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Unbreakable\ Kimmy\ Schmidt\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Unbreakable\ Kimmy\ Schmidt\ -\ \[* "$TV_SYM"/"Unbreakable Kimmy Schmidt"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Halt\ and\ Catch\ Fire\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Halt\ and\ Catch\ Fire\ -\ \[* "$TV_SYM"/"Halt and Catch Fire"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
if ls -U | grep -E 'Youre\ the\ Worst\ -\ \[*' >/dev/null 2>&1 ; then mv -v -S "-----Duplicate-${RANDOM_NUMBER}.mpeg" Youre\ the\ Worst\ -\ \[* "$TV_SYM"/"You're the Worst"/              2>/dev/null ; else false ; fi && echo -e "\n\n"
