#! /bin/bash
# Script to automate creating new OpenVPN clients

# Set where we're working from
OPENVPN_RSA_DIR=/etc/easy-rsa
OPENVPN_KEYS=/etc/openvpn/keys
KEY_DOWNLOAD_PATH=/etc/openvpn/CLIENTS

# Either read the CN from $1 or prompt for it
if [ -z "$1" ]
	then echo -n "Enter new client common name (CN): "
	read -e CN
else
	CN=$1
fi

# Ensure CN isn't blank
if [ -z "$CN" ]
	then echo "You must provide a CN."
	exit
fi

# Check the CN doesn't already exist
if [ -f $OPENVPN_KEYS/$CN.crt ]
	then echo "Error: certificate with the CN $CN alread exists!"
		echo "    $OPENVPN_KEYS/$CN.crt"
	exit
fi

# Enter the easy-rsa directory and establish the default variables
cd $OPENVPN_RSA_DIR

# Copied from build-key script (to ensure it works!)
export EASY_RSA="${EASY_RSA:-.}"
 sudo easyrsa build-client-full "$CN" nopass

# Take the new cert and place it somewhere it can be downloaded securely
 sudo rsync -avhP $OPENVPN_KEYS/$CN.crt $OPENVPN_KEYS/$CN.key $OPENVPN_KEYS/ca.crt /etc/openvpn/CLIENTS/"$CN"/

# Celebrate!
echo ""
echo "#############################################################"
echo "COMPLETE! Download the new certificate here:"
echo "$KEY_DOWNLOAD_PATH/$CN"
echo "#############################################################"
