#! /bin/bash
# Script to automate creating new OpenVPN servers

# Set where we're working from
OPENVPN_RSA_DIR=/etc/easy-rsa
OPENVPN_KEYS=/etc/openvpn/keys
KEY_DOWNLOAD_PATH=/etc/openvpn/CLIENTS

# Either read the CN from $1 or prompt for it
if [ -z "$1" ]
	then echo -n "Enter new server common name (CN): "
	read -e CN
else
	CN=$1
fi

# Ensure CN isn't blank
if [ -z "$CN" ]
	then echo "You must provide a CN."
	exit
fi


# Enter the easy-rsa directory and establish the default variables
	cd /etc/easy-rsa
	easyrsa init-pki
	easyrsa build-ca nopass
	easyrsa build-server-full "$CN" nopass
	openssl dhparam -out /etc/openvpn/dh.pem 2048
	openvpn --genkey --secret /etc/openvpn/ta.key
	


# Take the new cert and place it somewhere it can be downloaded securely
	sudo rsync -a pki/issued/$CN.crt pki/private/$CN.key pki/private/ca.crt /etc/openvpn/


# Celebrate!
echo ""
echo "#############################################################"
echo "COMPLETED! Find the new certificates here:"
echo "/etc/openvpn/"
echo "#############################################################"
