#! /bin/bash
# Script to automate creating new OpenVPN clients

# Set where we're working from
OPENVPN_RSA_DIR=/etc/easy-rsa
OPENVPN_KEYS=/etc/openvpn/keys
KEY_DOWNLOAD_PATH=/etc/openvpn/CLIENTS

# Either read the CN from $1 or prompt for it
if [ -z "$1" ]
	then echo -n "Enter new client common name (CN): "
	read -e CN
else
	CN=$1
fi

# Ensure CN isn't blank
if [ -z "$CN" ]
	then echo "You must provide a CN."
	exit
fi

echo "Server address?:"
read -e address
echo "Server port?:"
read -e port


# Enter the easy-rsa directory and establish the default variables
cd $OPENVPN_RSA_DIR

# Create the user
	sudo easyrsa build-client-full "$CN" nopass

# Create Needed directories
sudo mkdir /etc/openvpn/keys 2>/dev/null
sudo mkdir /etc/openvpn/CLIENTS 2>/dev/null
sudo mkdir /etc/openvpn/ccd 2>/dev/null


# Take the new cert and place it somewhere it can be downloaded securely
	sudo rsync -a pki/issued/$CN.crt pki/private/$CN.key /etc/openvpn/ca.crt /etc/openvpn/ta.key /etc/openvpn/CLIENTS/"$CN"/
	sudo rm pki/reqs/$CN.req pki/private/$CN.key pki/issued/$CN.crt

cd /etc/openvpn/CLIENTS/"$CN"/
	sudo mkdir Android 2>/dev/null
	sudo openssl pkcs12 -export -inkey $CN.key -in $CN.crt -certfile ca.crt -out Android/$CN.p12

	echo "# Sample File for openvpn client $CN"    | sudo tee -a /etc/openvpn/ccd/"$CN"
	echo "#   iroute 192.168.1.0 255.255.255.248"  | sudo tee -a /etc/openvpn/ccd/"$CN"
        echo "#   ifconfig-push 11.1.1.111 11.1.1.112" | sudo tee -a /etc/openvpn/ccd/"$CN"
	
	sudo chmod 775 /etc/openvpn/CLIENTS -R 


# Create ovpn file
/usr/local/bin/openvpn-ovpn-creator "$address" "$port" "/etc/openvpn/ca.crt" "$CN.crt" "$CN.key" "/etc/openvpn/ta.key" | sudo tee -a /etc/openvpn/CLIENTS/"$CN"/"$CN".ovpn

# Celebrate!
echo ""
echo "#############################################################"
echo "COMPLETED! Download the new certificates here:"
echo "Regular: $KEY_DOWNLOAD_PATH/$CN"
echo "Android $KEY_DOWNLOAD_PATH/$CN/Android"
echo "#############################################################"


echo "Where to copy the client file to:?   (eg:/x/xx/xxx/)"
read -e copyplace

echo " Coping from ($KEY_DOWNLOAD_PATH/$CN) to ($copyplace)" 


[ ! -z $copyplace ] && sudo rsync -avh --chmod 777 "$KEY_DOWNLOAD_PATH/$CN" "$copyplace"
