#!/bin/sh

##
## Usage: ./ovpn-writer.sh SERVER CA_CERT CLIENT_CERT CLIENT_KEY SHARED_SECRET > client.ovpn
##

server=${1?"The server address is required"}
port=${2?"The server port is required"}
cacert=${3?"The path to the ca certificate file is required"}
client_cert=${4?"The path to the client certificate file is required"}
client_key=${5?"The path to the client private key file is required"}
tls_key=${6?"The path to the TLS shared secret file is required"}

cat << EOF
client
dev tun
remote ${server}
port ${port}
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
verb 3
keepalive 10 120
proto udp
comp-lzo
remote-cert-tls server
<ca>
EOF
sudo cat ${cacert}
cat << EOF
</ca>
<cert>
EOF
sudo cat ${client_cert}
cat << EOF
</cert>
<key>
EOF
sudo cat ${client_key}
cat << EOF
</key>
<tls-auth>
EOF
sudo cat ${tls_key}
cat << EOF
</tls-auth>
EOF
