#! /bin/bash
# Script to automate creating new OpenVPN servers

# Set where we're working from
OPENVPN_RSA_DIR=/etc/easy-rsa
OPENVPN_KEYS=/etc/openvpn/keys
KEY_DOWNLOAD_PATH=/etc/openvpn/CLIENTS

# Either read the CN from $1 or prompt for it
if [ -z "$1" ]
	then echo -n "Enter new client common name (CN): "
	read -e CN
else
	CN=$1
fi

# Ensure CN isn't blank
if [ -z "$CN" ]
	then echo "You must provide a CN."
	exit
fi


# Enter the easy-rsa directory and establish the default variables
cd $OPENVPN_RSA_DIR

# Create the user
	sudo easyrsa build-client-full "$CN" nopass

# Take the new cert and place it somewhere it can be downloaded securely
	sudo rsync -a pki/issued/$CN.crt pki/private/$CN.key $OPENVPN_KEYS/ca.crt /etc/openvpn/CLIENTS/"$CN"/

cd /etc/openvpn/CLIENTS/"$CN"/
	sudo mkdir Android
	sudo openssl pkcs12 -export -inkey $CN.key -in $CN.crt -certfile ca.crt -out Android/$CN.p12

# Celebrate!
echo ""
echo "#############################################################"
echo "COMPLETED! Download the new certificates here:"
echo "Regular: $KEY_DOWNLOAD_PATH/$CN"
echo "Android $KEY_DOWNLOAD_PATH/$CN/Android"
echo "#############################################################"
