#!/bin/bash
# Reboot script


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


echo -e " Do you want to Reboot? 	y "
read confirmation
if [ "$confirmation" = "y" ]
then
sudo reboot
else
_CANCEL_MSG
fi



