#!/bin/bash
# Show current time notification
SCRIPT_NAME="show-time"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

# Generate gregorian date
DATE="$( date +%A\ %d\ %B\ \ \ \(%r\) )"

# Generate hijri date
DAY="$( date +%_d | sed 's/^ //' )"
MONTH="$( date +%_m | sed 's/^ //' )"
YEAR="$( date +%Y )"

HIJRI="$( curl -s "http://www.islamicfinder.org/dateConversion.php?mode=ger-hij&day=$DAY&month=$MONTH&year=$YEAR&date_result=1&lang=english" | grep -o -P '(?<=The conversion result is: </b> ).*(?=<br>\*There is a small probability)' )"

notify-send "$DATE" "$DATE $HIJRI"
