#!/bin/bash

SCRIPT_NAME="startup-programs"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


sudo systemctl restart couchpotato
sudo systemctl restart sickbeard
sudo systemctl restart sabnzbd

