#!/bin/bash
# do Tvnamer on media files
SCRIPT_NAME="tv"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


sudo chmod 777 * ; sudo chown "$USERNANE":"$USERNAME" *

PURPLE

tvnamer -c ~/.tvnamer.json *

RED

tvnamer -c ~/.tvnamer.json * |grep skipping 

exit 0
