#!/bin/bash
# Do a Tvnamer on media files & Move episodes
SCRIPT_NAME="tv-move"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


# Integration with dolphin tvnamer script
if [ -z "$TV_PATH" ];
then
        export TV_DOWNLOAD_DIR="$TV_DOWNLOAD_DIR"
else
        export TV_DOWNLOAD_DIR="$TV_PATH"

fi


# Clean the download folder
/usr/local/bin/clean-download-folder


cd "$TV_DOWNLOAD_DIR" || exit 1

sudo chmod 777 * ; sudo chown "$USERNANE":"$USERNAME" *

PURPLE

tvnamer -c ~/.tvnamer.json * | tee -a .Rename.Log ; date >> .Rename.Log

RED

tvnamer -c ~/.tvnamer.json * | grep skipping | tee -a .Rename.Log ; date >> .Rename.Log

CYAN

echo -e "${YELLOW}\n\n\n\nDo you want to Move?           y\n\n\n\n"

read confirmation

if [ "$confirmation" = "y" ]

then

filebot -get-missing-subtitles --lang en -non-strict *

/usr/local/bin/move 2>&1 | tee -a .Move.Log ; date >> .Move.Log


#if [ -n "$TERM_LAUNCH" ]
#then sleep 3
#fi


exit 0

else

_CANCEL_MSG

fi
