#!/bin/bash
# The RSYNC MOAS (Mother of All Scripts)
#SCRIPT_NAME="VAR-SCRIPT-RSYNC"
#PID=$$



#########################  Rsync exclude list ##########################

#####################  11-media*  ########################
# Change the excluded directories & files
echo "

lost*found
Home-Backup/*/*
Backups/*/*
Other/Android/.*
Other/Apps/NO-SYNC/*/*
Other/Downloads/temp/*
Other/Shows-clean/*
.Trash*
.directory
.mount-check

" >| "$RSYNC_EXCLUDE_11"


##########################  12-home* / 14-home* #################################
# Change the excluded directories & files
echo "

.ABZ-LOCKS/*
.gvfs/
.kde/
.config/google-chrome*
.cache/
.dropbox/
.local/
.mozilla/*.log
.macromedia/
.nv
.thumbnails/
.kodi/userdata/Thumbnails
*.socket
*.pipe
*.log
.directory
Dropbox/.dropbox*
Private
Private2
TMP/full-temp/*


" >| "$RSYNC_EXCLUDE_22"






##########################  14-media-offsite clean media only #################################
# Change the included directories & files
echo "

Shows
Shows/24/***

Movies
Movies/A Goofy Movie (1995)/***

- *


" >| "$RSYNC_EXCLUDE_33"




##########################  18-home-dots* #################################
# Change the excluded directories & files
echo "

.cache
.dropbox
.dropbox-dist
.ecryptfs
.kodi
.ssh
.thumbnails


" >| "$RSYNC_EXCLUDE_44"











#########################  Snapshot Variables ##################################

##Todays date:
export DAY0=$(date -I)
##Yesterdays date:
export DAY1=$(date -I -d "1 day ago")
##This Hour:
export HOUR0="$(date +%p-%H)"
##Previous Hour
export HOUR1="$(date +%p-%H -d "1 hour ago")"
##This Minute:
export MIN0="$(date +%M)"
##Previous Minute:
export MIN1="$(date +%M -d "1 minute ago")"
##10 days ago in ISO-8601 format
export DAY10=$(date -I -d "10 days ago")
##30 days ago in ISO-8601 format
export DAY30=$(date -I -d "30 days ago")
##60 days ago in ISO-8601 format
export DAY60=$(date -I -d "60 days ago")


###Delete the backup from 29 days ago, if it exists
##if [ -d /backup/website/$DAY29 ]
##then
##rm /backup/website/$DAY29
##fi



########################### RSYNC #############################

#################################################### /
# NOTE:                                              /
#	 when TRG is in SRC folder                   /
#	 rsync must be = "$SRC_15"*  (Notice the *)  /
#	 to avoid duplication of TRG                 /
#################################################### /

####################################################

export SNAPSHOT_DIR="Snapshots/$DAY0/$HOUR0"

export SNAPSHOT_DIR_OLD="Snapshots/$DAY10"

export RSYNC_LOG="logs/$SCRIPT_NAME-$DAY0-$HOUR0"

export LINK_SYM="current"


###############################################################

#The source directory:
export SRC_11="/media/R1/"
export SRC_11_2="/media/R1/"

#The target directory:
export TRG_11="/media/R1/Backups/Media/$SNAPSHOT_DIR"
export TRG_11_2="/media/R1/Backups/Media/$SNAPSHOT_DIR-small"
#export TRG_11_OLD="/media/R1/Backups/Media/$SNAPSHOT_DIR_OLD"

#The link destination directory:
export LNK_11="/media/R1/"
export LNK_11_2="/media/R1/"

#The Log file
export LOG_11="/media/R1/Backups/$RSYNC_LOG"
export LOG_11_2="/media/R1/Backups/$RSYNC_LOG"

# Rsync Options
OPT_11=("-iavhHP"  "--exclude-from=$RSYNC_EXCLUDE_11" "--link-dest=$LNK_11")
OPT_11_2=("-iavhHP"  "--exclude-from=$RSYNC_EXCLUDE_11" "--max-size=15M")
# OPT_11_2 has no (link dest) so it will make new copies of files less than 15MB

###############################################################

#The source directory:
export SRC_12="$MYHOME/"
export SRC_12_2="$MYHOME/"

#The target directory:
export TRG_12="$HOME_BACKUP_FOLDER/$SNAPSHOT_DIR"
export TRG_12_OLD="$HOME_BACKUP_FOLDER/$SNAPSHOT_DIR_OLD"

export TRG_12_2="$HOME_BACKUP_FOLDER/ALL"
#export TRG_12_2_OLD="$HOME_BACKUP_FOLDER2/$SNAPSHOT_DIR_OLD"


#The link destination directory:
export LNK_12="$HOME_BACKUP_FOLDER/$LINK_SYM"
#export LNK_12_2="$HOME_BACKUP_FOLDER2/$LINK_SYM"


#The Log file
export LOG_12="$HOME_BACKUP_FOLDER/$RSYNC_LOG"
#export LOG_12_2="$HOME_BACKUP_FOLDER2/$RSYNC_LOG"

#The rsync options:
OPT_12=("-iavhHP" "--link-dest=$LNK_12" "--exclude-from=$RSYNC_EXCLUDE_22" "--log-file=$LOG_12")
OPT_12_2=("-biavhHP" "--exclude-from=$RSYNC_EXCLUDE_22")
OPT_12_TAR=(--exclude='Private/*' --exclude='Private2/*' --exclude='.kodi' --exclude='.thumbnails/*' --exclude='.cache/*' --exclude='TMP/full-temp/*')


###############################################################

#The source directory:
SRC_13="/etc"

#The target directory:
TRG_13="$ETC_BACKUP_FOLDER/Snapshots/$DAY0/$HOUR0"


###############################################################

#The source directory:
export SRC_14="/media/R1/"

#The target directory:
export TRG_14="/media/C3/"

#The rsync options: ( Array ooooh :) )
OPT_14=("-iavhP" "--del" "--include-from=$RSYNC_EXCLUDE_33")


###############################################################

#The source directory:
export SRC_15="/usr/local/bin/"

#The target directory:
export TRG_15="/home/abz/Ares/My-Scripts/ArchLinux/Snapshots/$DAY0/$HOUR0"


###############################################################

#The source directory:
export SRC_16="/usr/share/webapps/"

#The target directory:
export TRG_16="/home/abz/Ares/My-Website/sderawi.dyndns.org/$DAY0"

# Tar Options
export OPT_16=""


###############################################################

#The source directory:
export SRC_17="/home/abz/Open-Office/Tips-and-Tricks/"

#The target directory:
export TRG_17="/home/abz/Open-Office/Tips-and-Tricks/.Backups/Snapshots/$DAY0/$HOUR0"

# Tar Options
export OPT_17="--exclude=.*"


###############################################################

#The source directory:
export SRC_18="$MYHOME"

#The target directory:
export TRG_18="/home/abz/Ares/Dot-Files"

#The rsync options:
OPT_18=("-iavhHP" "--del" "--safe-links" "--exclude-from=$RSYNC_EXCLUDE_44")


###############################################################
