#!/bin/bash
# Create "xspf" files for vlc to read from
SCRIPT_NAME="vlc-helper"
PID=$$

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

# Run <script_name> -c to check if the script is running
if [[ "$1" = "-c"* ]] ;then _LOCK_CHECK ; fi

# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################

TMP="$(mktemp)"
TMP2="$(mktemp)"

echo "Searching for TV files without VLC XSPF files"
echo ""

_CHECK_MOUNT1 && \
find "$TV_SYM"/ -size +25M  -iname "hogans heroes*1x01*" > $TMP

while read file
do

# To get the filename without extensions
FILENAME="$(echo "$file" | rev | cut -d"." -f2- | rev)"

if [ ! -f "$FILENAME"*.xspf ]
then

FILE="$(echo "$file" | sed -e 's| |%20|g' \
-e 's|!|%21|g' \
-e 's|#|%23|g' \
-e 's|\$|%24|g' \
-e 's|&|%26|g' \
-e "s|'|%27|g" \
-e 's|(|%28|g' \
-e 's|)|%29|g' \
-e 's|*|%2A|g' \
-e 's|+|%2B|g' \
-e 's|,|%2C|g' \
-e 's|:|%3A|g' \
-e 's|;|%3B|g' \
-e 's|=|%3D|g' \
-e 's|?|%3F|g' \
-e 's|@|%40|g' \
-e 's|\[|%5B|g' \
-e 's|\]|%5D|g' \
-e 's|>|%3E|g' \
-e 's|<|%3C|g' \
-e 's|{|%7B|g' \
-e 's|}|%7D|g' \
-e 's|_|%5F|g' \
-e 's|\^|%5E|g' \
-e 's|\||%7C|g')"

# Not needed for vlc but good for url encoding
#-e 's|-|%2D|g'
#-e 's|/|%2F|g'
#-e 's|\.|%2E|g'

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<playlist xmlns=\"http://xspf.org/ns/0/\" xmlns:vlc=\"http://www.videolan.org/vlc/playlist/ns/0/\" version=\"1\">
	<title>"$(basename "$file")"</title>
	<trackList>
		<track>
			<location>file://"$FILE"</location>
			<extension application=\"http://www.videolan.org/vlc/playlist/0\">
				<vlc:id>0</vlc:id>
				<vlc:option>start-time=0</vlc:option>
			</extension>
		</track>
	</trackList>
	<extension application=\"http://www.videolan.org/vlc/playlist/0\">
			<vlc:item tid=\"0\"/>
	</extension>
</playlist>

" >> "$FILENAME".xspf

echo "$file".xspf

fi


done < $TMP

	

#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF


