#!/bin/bash
# Replay last video file if wanted
SCRIPT_NAME="vlc-alternate-player-repeat"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON



#########################################################
[ -z "$1" ] && echo "No video specified" && exit 1 


dialog --stdout  --clear --yesno "Replay Video file again :

$FILENAME2 " 10 50




case $? in
0) 
/usr/local/bin/vlc-alternate-player "$(cat $PLAYER_LAST_WATCHED/Last-Video.txt)"

;;
1) 
exit 1 ;;
esac


#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

