#!/bin/bash
# Write notes on selected video from KODI
SCRIPT_NAME="vlc-note-taker"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

# Run <script_name> -c to check if the script is running
if [[ "$1" = "-c"* ]] ;then _LOCK_CHECK ; fi

# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################
FNAME="$1"

if [ ! -z "$FNAME" ]
then

# To get the filename without extensions
FILENAME="$(echo "$FNAME" | rev | cut -d"." -f2- | rev)"
# To get the filename only without the whole path
FILENAME2="$(basename "$FNAME")"

NOTE="$FILENAME-NOTES.txt"

 
sudo nano "$NOTE"
sudo chown "$USERNAME" "$NOTE"
sudo chmod 777 "$NOTE"

else
echo "No video specified"
exit 1 
 
fi

#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

