#!/bin/bash
# Write notes on selected video from KODI
SCRIPT_NAME="vlc-note-taker"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

# Run <script_name> -c to check if the script is running
if [[ "$1" = "-c"* ]] ;then _LOCK_CHECK ; fi

# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################
FNAME="$1"

[ -z "$FNAME" ] && echo "No video specified" && exit 1 
 
terminator -x /usr/local/bin/vlc-note-taker-helper "$FNAME" 2>/dev/null


#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

