#!/bin/bash
# Wrapper for vlc that checks for xspf files
SCRIPT_NAME="vlc-alternate-player"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT




#########################################################
export FNAME="$1"


TMP="$(mktemp)"
TIME_TMP="$(mktemp)"

# To get the filename without extensions
FILENAME="$( echo "$FNAME" | rev | cut -d"."  -f2- | rev )"
# To get the filename without the path
FILENAME2="$( echo "$FNAME" | rev | cut -d"/" -f1  | rev )"
# To get the path without the filename
FILENAME3="$( dirname "$FNAME" )"

touch /tmp/vcheck1
while [ -f /tmp/vcheck1 ] ; do [ -f /tmp/vcheck2 ] && curl -s -u ":vlcremote" http://127.0.0.1:8888/requests/status.json | grep time | sed 's/,//g' |cut -b 10- >> $TIME_TMP &&  sleep 1 || sleep 1  ; done &



if [ -f "$FILENAME"*.xspf ]

then 

	if 
	
		# Find if we need Subs Really
		[ "$(cat "$FILENAME3"/1-info)" = "No Need For Subs" ]
	
	then
		echo "No Need For Subs"
	
	else

		[ -f "$(ls "$FILENAME"*.srt 2>/dev/null |head -n1)" -o -f "$(ls "$FILENAME"*.sub 2>/dev/null |head -n1)" ] || terminator -x filebot -get-missing-subtitles --lang en -non-strict "$FNAME"
		[ -f "$(ls "$FILENAME"*.srt 2>/dev/null |head -n1)" -o -f "$(ls "$FILENAME"*.sub 2>/dev/null |head -n1)" ] || (notify-send "Media" "Subtitle Not Found"  &&  sudo beep)

	fi

	

	echo "" >> "$PLAYER_LAST_WATCHED"/"$DAY0".txt
	echo "$(date | cut -d" " -f 1-5) <-> Started  - ($FILENAME2)" >> "$PLAYER_LAST_WATCHED"/"$DAY0".txt

	# REPEAT variable comes from the repeater script to prevent clogging this file needlessly
	[ -z "$REPEAT" ] && echo "$FNAME" >> "$PLAYER_LAST_WATCHED"/"Last-Video".txt


	START_TIME=$(date +%s)

	
	if [ -f "$FNAME".time.txt ]
	then 
touch /tmp/vcheck2
	vlc "$FNAME" --start-time "$(sed '/^$/d;s/^ $//g' "$FNAME".time.txt | tail -n1)" --play-and-exit --extraintf=http --http-host 127.0.0.1 --http-port 8888 --http-password 'vlcremote' 2>&1 >/dev/null
rm /tmp/vcheck2
echo "$(cat $TIME_TMP| sed '/^$/d;/^0$/d;s/^[ \t]*//;s/[ \t]*$//' |tail -n1)" >> "$FNAME".time.txt
rm /tmp/vcheck1


	else vlc "$FILENAME"*.xspf --play-and-exit --extraintf=http --http-host 127.0.0.1 --http-port 8888 --http-password 'vlcremote' 2>&1 >/dev/null
	fi


	KODI_LAST_WATCHED="$(ls -t ~/.kodi/userdata/Database/MyVideo* |head -n 1)" && sqlite3  "$KODI_LAST_WATCHED" "select strFilename, playCount from files where strFilename like '%$FILENAME2' ;" | head -n1  | sed 's/^|1//g;/|$/d;s/^[ \t]*//;s/[ \t]*$//;/^$/d' | cut -d"|" -f1 >> $TMP


else 
	
		if 
	
		# Find if we need Subs Really
		[ "$(cat "$FILENAME3"/1-info)" = "No Need For Subs" ]
	
		then
		echo "No Need For Subs"
	
		else

		[ -f "$(ls "$FILENAME"*.srt 2>/dev/null |head -n1)" -o -f "$(ls "$FILENAME"*.sub 2>/dev/null |head -n1)" ] || terminator -x filebot -get-missing-subtitles --lang en -non-strict "$FNAME"
		[ -f "$(ls "$FILENAME"*.srt 2>/dev/null |head -n1)" -o -f "$(ls "$FILENAME"*.sub 2>/dev/null |head -n1)" ] || (notify-send "Media" "Subtitle Not Found"  &&  sudo beep)

		fi


	echo "" >> "$PLAYER_LAST_WATCHED"/"$DAY0".txt
	echo "$(date | cut -d" " -f 1-5) <-> Started  - ($FILENAME2)" >> "$PLAYER_LAST_WATCHED"/"$DAY0".txt

	# REPEAT variable comes from the repeater script to prevent clogging this file needlessly
	[ -z "$REPEAT" ] && echo "$FNAME" >> "$PLAYER_LAST_WATCHED"/"Last-Video".txt



	START_TIME=$(date +%s)
	
	if [ -f "$FNAME".time.txt ]
	then vlc "$FNAME" --start-time "$(tail -n1 "$FNAME".time.txt)" --play-and-exit --extraintf=http --http-host 127.0.0.1 --http-port 8888 --http-password 'vlcremote' 2>&1 >/dev/null
	else vlc "$FNAME"*.xspf --play-and-exit --extraintf=http --http-host 127.0.0.1 --http-port 8888 --http-password 'vlcremote' 2>&1 >/dev/null
	fi
	
	while curl -s -u ":vlcremote" http://127.0.0.1:8888/requests/status.xml >/dev/null ; do VLC_TIME="$(curl -s -u ":vlcremote" http://127.0.0.1:8888/requests/status.xml | grep time |cut -d"/" -f1 | sed 's/<time>//g;s/<//g' >> $TIME_TMP )" && sleep .5 || (export VLC_TIME="$(cat $TIME_TMP| sed 's/^$/d')" && break) ;done && echo "$VLC_TIME" >> "$FNAME.time.txt"

	KODI_LAST_WATCHED="$(ls -t ~/.kodi/userdata/Database/MyVideo* |head -n 1)" && sqlite3  "$KODI_LAST_WATCHED" "select strFilename, playCount from files where strFilename like '%$FILENAME2' ;" | head -n1  | sed 's/^|1//g;/|$/d;s/^[ \t]*//;s/[ \t]*$//;/^$/d' | cut -d"|" -f1 >> $TMP

fi



END_TIME=$(date +%s)
END_TIME_SEC=$(( END_TIME - START_TIME ))

[ "$END_TIME_SEC" -gt 60 ] &&  echo "$(date | cut -d" " -f 1-5) <-> Finished - ($FILENAME2)" >> "$PLAYER_LAST_WATCHED"/"$DAY0".txt

nohup sleep 1 && while read a ; do notify-send "Media" "$a \n\nMarked as Watched" ; done < $TMP &

