#!/bin/bash
# Replay last video file if wanted
SCRIPT_NAME="vlc-alternate-player-repeat"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON



#########################################################
TMP1="$(mktemp)"
TMP2="$(mktemp)"
TMP3="$(mktemp)"
TMP4="$(mktemp)"
TMP5="$(mktemp)"
TMP6="$(mktemp)"

CLEAN_TMP_FILES()
{	
rm "$TMP1" "$TMP2" "$TMP3" "$TMP4" "$TMP5" 2>/dev/null
}

# Get the file name from Last-video.txt
FILE="$(cat "$PLAYER_LAST_WATCHED"/Last-Video.txt | tail -n 1)"

# F_ARRAY = Full file path , eg: /X/X/X.avi
while read a ; do F_ARRAY+=("$a") ; done < <(uniq "$PLAYER_LAST_WATCHED"/Last-Video.txt | tail -n 3)

for i in 0 1 2 ; do basename "${F_ARRAY[$i]}" ; done >> "$TMP2"
sed -i '/^$/d' "$TMP1"
sed -i '/^$/d' "$TMP2"

# F2_ARRAY = Filename Only , eg: X.avi
while read b ; do F2_ARRAY+=("$b") ; done < "$TMP2"
for i in 0 1 2 ; do  echo "${F_ARRAY[$i]}" | rev | cut -d"." -f2- | rev  ; done >> "$TMP4"
sed -i '/^$/d' "$TMP4"

# F3_ARRAY = Full File path without extensions , eg: /X/X/X/X
while read c ; do F3_ARRAY+=("$c") ; done <  "$TMP4"

# F4_ARRAY = Parent dir of File , eg: /X/X/X/
while read d ; do F4_ARRAY+=("$d") ; done < "$TMP1"
for i in 0 1 2 ; do  dirname "${F4_ARRAY[$i]}" ; done >> "$TMP5"


KODI_LAST_WATCHED="$(ls -t ~/.kodi/userdata/Database/MyVideo* |head -n 1)" &&\
sqlite3  "$KODI_LAST_WATCHED" "select strFilename, playCount from files order by lastPlayed desc;" | head -n100  | sed 's/^|1//g;/|$/d;s/^[ \t]*//;s/[ \t]*$//;/^$/d' | cut -d"|" -f1 >> "$TMP6"


# Remove All Blank Lines
sed -i '/^$/d' "$TMP6"


PLAY()
{
	[ "$1" = "FIRST" ]  && VALUE="2" && LETTER="A"
	[ "$1" = "SECOND" ] && VALUE="1" && LETTER="B"
	[ "$1" = "THIRD" ]  && VALUE="0" && LETTER="C"
	[ -z "$1" ]         && (echo "No file selected" ; return 1)
	
	FILENAME_ONLY="${F2_ARRAY[$VALUE]}"
	FULL_PATH="${F_ARRAY[$VALUE]}"
	FULL_PATH_NO_EXT="${F3_ARRAY[$VALUE]}"
	PARENT_DIR="${F4_ARRAY[$VALUE]}"
	
	dialog --stdout --checklist "Options for: (  $FILENAME_ONLY  )" 13 100 5 \
	"Repeat Video"				"" on \
	"Remove Video Subtitles"	"" off \
	"Take Notes"				"" off \
	"Forget Saved Position"		"" off \
	"Open in Dolphin"			"" off > "$TMP3"

	grep --fixed-strings "Take Notes" "$TMP3" && /usr/local/bin/vlc-note-taker "$FULL_PATH"
	grep --fixed-strings "Remove Video Subtitles" "$TMP3" && (rm "$FULL_PATH_NO_EXT"*.srt ; rm "$FULL_PATH_NO_EXT"*.sub)
	grep --fixed-strings "Forget Saved Position" "$TMP3" && rm "$FULL_PATH_NO_EXT".time.txt
	grep --fixed-strings "Open in Dolphin" "$TMP3" && dolphin "$PARENT_DIR"
	grep --fixed-strings "Repeat Video" "$TMP3" && export REPEAT=ON && \
	[ ! -z "$LETTER" ] && nohup /usr/local/bin/vlc-alternate-player "$FULL_PATH" >/dev/null 2>&1 &
	sleep .3

}

grep --fixed-strings "${F2_ARRAY[2]}" "$TMP6" && A="${GREENz}[Y]${COLORz_OFF}  -  ${F2_ARRAY[2]}" || A="${REDz}[N]${COLORz_OFF}  -  ${F2_ARRAY[2]}"
grep --fixed-strings "${F2_ARRAY[1]}" "$TMP6" && B="${GREENz}[Y]${COLORz_OFF}  -  ${F2_ARRAY[1]}" || B="${REDz}[N]${COLORz_OFF}  -  ${F2_ARRAY[1]}"
grep --fixed-strings "${F2_ARRAY[0]}" "$TMP6" && C="${GREENz}[Y]${COLORz_OFF}  -  ${F2_ARRAY[0]}" || C="${REDz}[N]${COLORz_OFF}  -  ${F2_ARRAY[0]}"


SELECTION="$(dialog --stdout --colors --clear --radiolist \
"Select Video File:   (1 = Newest /  3 = Oldest)" 13 100 5 \
1 "$A" on \
2 "$B" off \
3 "$C" off )"


case $? in
0) 

	case "$SELECTION" in
	1)
		PLAY "FIRST"
	;;
	2)
		PLAY "SECOND"
	;;
	3)
		PLAY "THIRD"
	;;
	esac

;;
1) 
exit 1 ;;
esac


CLEAN_TMP_FILES

#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

