#!/bin/bash
# Wrapper for vlc that checks for xspf files
SCRIPT_NAME="vlc-progress-monitor"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT




#########################################################
FNAME="$1"


TMP="$(mktemp)"
TIME_TMP="$(mktemp)"

# To get the filename without extensions
FILENAME="$( echo "$FNAME" | rev | cut -d"."  -f2- | rev )"
# To get the filename without the path
FILENAME2="$( echo "$FNAME" | rev | cut -d"/" -f1  | rev )"
# To get the path without the filename
FILENAME3="$( dirname "$FNAME" )"





while curl -s -u ":vlcremote" http://127.0.0.1:8888/requests/status.xml ; do VLC_TIME="$(curl -s -u ":vlcremote" http://127.0.0.1:8888/requests/status.xml | grep time |cut -d"/" -f1 | sed 's/<time>//g;s/<//g' >> $TIME_TMP )" && sleep .5 || (export VLC_TIME="$(cat $TIME_TMP| sed 's/^$/d')" && break) ;done && echo "$VLC_TIME" >> "$FNAME.time.txt"
