#!/bin/bash
# Replay last video file if wanted
SCRIPT_NAME="vlc-alternate-player-repeat"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT


# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON



#########################################################
TMP="$(mktemp)"

# Get the file name from Last-video.txt
FILE="$(cat "$PLAYER_LAST_WATCHED"/Last-Video.txt | tail -n 1)"

while read a ; do F_ARRAY+=("$a") ; done < <(tail -n 3 "$PLAYER_LAST_WATCHED"/Last-Video.txt)
for i in 0 1 2 ; do basename "${F_ARRAY[$i]}" ; done >> $TMP
while read b ; do F2_ARRAY+=("$b") ; done <  $TMP

# To get the filename without extensions
FILENAME="$(echo "$FILE" | rev | cut -d"." -f2- | rev )"

# To get the filename without the path
FILENAME2="$(echo "$FILE" | rev | cut -d"/" -f1 | rev )"

SELECTION="$(dialog --stdout --radiolist \
"Select Video File:   (1= Newest -  3= Oldest)" 10 100 3 \
1 "${F2_ARRAY[2]}" on \
2 "${F2_ARRAY[1]}" off \
3 "${F2_ARRAY[0]}" off )"


#dialog --stdout  --clear --yesno "Replay Video file again :

#$FILENAME2 " 10 50




case $? in
0) 

	# To prevent the repeating action from clogging the Last-video.txt file
	export REPEAT=ON

	case "$SELECTION" in
	1)
	/usr/local/bin/vlc-alternate-player "${F_ARRAY[2]}" ;;
	2)
	/usr/local/bin/vlc-alternate-player "${F_ARRAY[1]}" ;;
	3)
x	/usr/local/bin/vlc-alternate-player "${F_ARRAY[0]}" ;;
	esac

;;
1) 
exit 1 ;;
esac


#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

