#!/bin/bash
# Wrapper for vlc that checks for xspf files
SCRIPT_NAME="vlc-alternate-player"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT




#########################################################
FNAME="$1"


export TMP="$(mktemp)"


# To get the filename without extensions
FILENAME="$(echo "$FNAME" | rev | cut -d"." -f2- | rev)"
# To get the filename without the path
FILENAME2="$(echo "$FNAME" | rev | cut -d"/" -f1 | rev)"

if [ -f "$FILENAME"*.xspf ]

then 

	[ -f "$(ls "$FILENAME"*.srt 2>/dev/null |head -n1)" -o -f "$(ls "$FILENAME"*.sub 2>/dev/null |head -n1)" ] || terminator -x filebot -get-missing-subtitles --lang en -non-strict "$FNAME"
	[ -f "$(ls "$FILENAME"*.srt 2>/dev/null |head -n1)" -o -f "$(ls "$FILENAME"*.sub 2>/dev/null |head -n1)" ] || (notify-send "Media" "Subtitle Not Found"  &&  sudo beep)

	echo "$(date | cut -d" " -f 1-4) <-> Started - ($FILENAME2)" >> "$PLAYER_LAST_WATCHED"/"$DAY0".txt

	# REPEAT variable comes from the repeater script to prevent clogging this file needlessly
	[ -z "$REPEAT" ] && echo "$FNAME" >> "$PLAYER_LAST_WATCHED"/"Last-Video".txt


	START_TIME=$(date +%s)

	vlc "$FILENAME"*.xspf --play-and-exit  2>&1 >/dev/null

	KODI_LAST_WATCHED="$(ls -t ~/.kodi/userdata/Database/MyVideo* |head -n 1)" &&\
	sqlite3  "$KODI_LAST_WATCHED" "select strFilename, playCount from files where strFilename like '%$FILENAME2' ;" | head -n1  | sed 's/^|1//g;/|$/d;s/^[ \t]*//;s/[ \t]*$//;/^$/d' | cut -d"|" -f1 >> $TMP


else 

	[ -f "$(ls "$FILENAME"*.srt 2>/dev/null |head -n1)" -o -f "$(ls "$FILENAME"*.sub 2>/dev/null |head -n1)" ] || terminator -x filebot -get-missing-subtitles --lang en -non-strict "$FNAME"
	[ -f "$(ls "$FILENAME"*.srt 2>/dev/null |head -n1)" -o -f "$(ls "$FILENAME"*.sub 2>/dev/null |head -n1)" ] || (notify-send "Media" "Subtitle Not Found" && sudo beep)

	echo "$(date | cut -d" " -f 1-4) <-> Started - ($FILENAME2)" >> "$PLAYER_LAST_WATCHED"/"$DAY0".txt

	# REPEAT variable comes from the repeater script to prevent clogging this file needlessly
	[ -z "$REPEAT" ] && echo "$FNAME" >> "$PLAYER_LAST_WATCHED"/"Last-Video".txt



	START_TIME=$(date +%s)

	vlc "$FNAME" --play-and-exit  2>&1 >/dev/null

	KODI_LAST_WATCHED="$(ls -t ~/.kodi/userdata/Database/MyVideo* |head -n 1)" &&\
	sqlite3  "$KODI_LAST_WATCHED" "select strFilename, playCount from files where strFilename like '%$FILENAME2' ;" | head -n1  | sed 's/^|1//g;/|$/d;s/^[ \t]*//;s/[ \t]*$//;/^$/d' | cut -d"|" -f1 >> $TMP

fi



END_TIME=$(date +%s)
END_TIME_SEC=$(( END_TIME - START_TIME ))
[[ "$END_TIME_SEC" -gt 10 ]] && echo "$FILENAME" | grep "/Movies/" && /usr/local/bin/vlc-note-taker "$FNAME"

nohup sleep 1 && while read a ; do notify-send "Media" "$a - Marked as Watched" ; done < $TMP &
