#!/bin/bash
# Fetch subtitles of selected video from XBMC
SCRIPT_NAME="vlc-subtitle-fetcher"
PID=$$


# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

# Run <script_name> -c to check if the script is running
if [[ "$1" = "-c"* ]] ;then _LOCK_CHECK ; fi

# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################
[ -z "$1" ] && echo "No video specified" && exit 1 

# To get the filename without extensions
FILENAME="$(echo "$1" | rev | cut -d"." -f2- | rev)"
FILENAME2="$(echo "$1" | rev | cut -d"/" -f1 | rev)"


 
terminator -x filebot -get-missing-subtitles --lang en -non-strict "$1"

[ -f "$(ls "$FILENAME"*.srt|head -n1)" -o -f "$(ls "$FILENAME"*.sub|head -n1)" ] || (notify-send "Media" "Subtitle Not Downloaded" && sudo beep)


#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

