#!/bin/bash
# Write notes on selected video from XBMC
SCRIPT_NAME="vlc-note-taker-helper"
PID=$$
set -x

# Source the VAR MOAS
source /usr/local/bin/VAR-SCRIPT

# Run <script_name> -c to check if the script is running
if [[ "$1" = "-c"* ]] ;then _LOCK_CHECK ; fi

# Time Calculation
_START_TIME

# Start Lock
_LOCK_ON

#########################################################
[ -z "$1" ] && echo "No video specified" && exit 1 

# To get the filename without extensions
FILENAME="$(echo "$1" | rev | cut -d"." -f2- | rev)"
NOTE="$FILENAME-NOTES.txt"

 

dialog --stdout  --clear --yesno "Make a note for the Movie :
$1  ?" 10 50

case $? in
0) 
sudo nano "$NOTE"
sudo chown "$USERNAME" "$NOTE"
sudo chmod 777 "$NOTE"

;;
1) exit 1 ;;
esac



#########################################################

# Time Calculation
_END_TIME

# End Lock
_LOCK_OFF

